- README.md
- requirements.txt
> Add requirements.txt and instructions to install dependencies with pip.

- README.md
- create-draft
- templates/LICENSE.md
- titlecase
1. Merge from master to pick up fixes.
2. Update Inkscape install step to use proper cask
3. Add md5sha1sum to brew line to get `sha1sum` command
> Merge latest master changes, fixup install instructions

- semanticate
Not sure if "Honorable" comes up enough to warrant adding, but it did come up in the book I'm working on.
> Add abbreviation for "Honorable"

- modernize-spelling
A couple more found during Moby Dick production. Vishnu modernisation is debatable, but I think trousers is definitely worth doing.
> More spelling modernisation

- modernize-spelling
Hope I've done this right! My regex includes the possibility of a straight single quote as well as right single quote.
> added bee's wax -> beeswax

- se/se_epub.py
This came up as an issue in this thread: https://groups.google.com/d/msg/standardebooks/1yLgBiwp3-0/q5w2Q2RnAAAJ
> Quote the problematic missing class name during linting

- README.md
Also fix the OS name and include 10.13 as tested.
> Brew now defaults python to Python 3

- modernize-spelling
I've checked all of these in Google's NGram viewer, and they all die out in early to mid 1800s. All found in "Emma".
> Added archaic spellings

- modernize-spelling
This was in "Clarissa Harlowe". Google NGram shows it to be (to me) surprisingly common up until mid 1800s.
> modernize-spelling: Added P/phrensy -> F/frenzy

- semanticate
This has come up in the Arsène Lupin stories.
> Add Mon. as an abbreviation of Monsieur

- modernize-spelling
Looks like the only occurrence (outside of the Conan stories I’m working on) is a couple of surprizes in Lovecraft, will leave those for you to fix up.
> Fix the surprize -> surprise regex

- modernize-spelling
Another antique spelling in "Clarissa Harlowe"
> modernize-spelling: Added controul -> control etc

- modernize-spelling
bowlder -> boulder
https://books.google.com/ngrams/graph?content=bowlder%2Cboulder&year_start=1800&year_end=2000&corpus=15&smoothing=3
alarum -> alarm
https://books.google.com/ngrams/graph?content=alarum%2Calarm&year_start=1800&year_end=2000&corpus=15&smoothing=3
> Modernize two more spellings

- se/se_epub.py
> Removed parameter from recompose-epub and code making ToC optional

- se/executables.py
- se/executables_make_toc.py
- se/se_epub.py
- se/se_epub_make_toc.py
Alex: I'm not at all sure I've done this correctly, particularly in how it's integrated with the other commands. Please review!
But **se make-toc .** does seem to work correctly.
> Added make-toc command to toolset.

- se/executables.py
- se/se_epub_generate_toc.py
This should address issues #138 and #139. Basically I'm doing a lot more checking for None objects.
> Fixed a number of bugs causing in crashes with projects in the corpus.

- se/se_epub_generate_toc.py
Cleaned this up. There was a lot of overlap between the two classes, and no real need to have them as separate. The TocItem class is now used both to collect data for Table of Contents entries and for Landmark entries.
> Combined Toc_item class and LandmarkItem class into single class

- se/spelling.py
This change updates the modernize-spelling tool to accept the en-AU and en-CA languages.
It also fixes a bug where 'language' was defined as a regex match rather than a language string, which caused language-specific updates to not be applied.
> Add support for en-AU and en-CA

- se/executables.py
- se/images.py
- se/se_epub_build.py
Same procedure as with Calibre.
I did wonder if these could be extracted into a helper function. Any thoughts on where it might go?
> Fix MathML code to use Mac Firefox if available

- README.md
> Add a macOS 10.15 compatibility warning

- .github/workflows/se-test.yml
> Use pipx to install packages for testing

- se/__init__.py
- se/epub.py
- se/executables.py
- se/executables_create_draft.py
- se/formatting.py
- se/images.py
- se/se_epub.py
- se/se_epub_build.py
- se/se_epub_generate_toc.py
- se/se_epub_lint.py
- se/spelling.py
- se/typography.py
- tests/conftest.py
- tests/helpers.py
- tests/test_build.py
- tests/test_lint.py
- tests/test_simple_cmds.py
- tests/test_text_cmds.py
Turns out there is a nice tool for automatically upgrading python code:
https://github.com/asottile/pyupgrade
I've updated all of the format() calls to fstrings. Tests still pass and I did a quick browse through and it all looked good.
> Use pyupgrade to convert .format() to fstrings

- .github/workflows/se-test.yml
- .gitignore
- mypy.ini
- se/__init__.py
- se/easy_xml.py
- se/formatting.py
- se/spelling.py
- se/typography.py
The mypy.ini config file allows us to specify which files to check, so I have enabled the checking for the files that I have cleaned up so far.
> Fix mypy errors, enable checking for clean files

- se/se_epub_generate_toc.py
- tests/conftest.py
- tests/data/lint/content-out.txt
- tests/data/print-manifest-and-spine/in/chapter-1.xhtml
- tests/data/print-manifest-and-spine/in/content.opf
- tests/data/print-manifest-and-spine/out/chapter-1.xhtml
- tests/data/print-manifest-and-spine/out/content.opf
- tests/data/print-toc/in/chapter-1.xhtml
- tests/data/print-toc/toc-out.txt
- tests/helpers.py
- tests/test_lint.py
- tests/test_print_toc.py
- tests/test_text_cmds.py
Added tests for print-toc and print-manifest-and-spine. Made some tweaks to improve the diff output of file comparisons when a test fails.
> Test updates

- mypy.ini
- se/__init__.py
- se/epub.py
- se/images.py
- se/se_epub.py
- se/se_epub_build.py
- se/se_epub_lint.py
- se/typography.py
You will notice that I changed all of the variables in the Endnote class from class variables to instance variables. There was actually a subtle bug lurking in the initialization of the `contents` field. The class variable provides an empty list as a default value, but a list is a mutable object. It's generally considered a bad idea to use mutable objects as default values. Here is why:
With mutable class variable:
>>> from se import se_epub
>>> a = se_epub.Endnote()
>>> b = se_epub.Endnote()
>>> a.contents.append("1")
>>> b.contents.append("2")
>>> a.contents
['1', '2']
>>> b.contents
['1', '2']
With instance variable:
>>> from se import se_epub
>>> a = se_epub.Endnote()
>>> b = se_epub.Endnote()
>>> a.contents.append("1")
>>> b.contents.append("2")
>>> a.contents
['1']
>>> b.contents …
> Final mypy fixes. All files are clean.

- se/se_epub.py
I had to hunt around for the correct media type, and it whole landscape seems really muddy. However this was suggested as correct, and it seems to work at least.
> Make sure that fonts are correctly included in the manifest

- README.md
> py3-gitdb is a new dependency

- se/spelling.py
Fixes https://github.com/standardebooks/tools/issues/257.
> Modernize up/down stairs -> up/downstairs

- se/se_epub_build.py
> Don't treat epubcheck output as failure, check return code instead

- se/formatting.py
Not very common but I ran across it so I added it. [https://en.wiktionary.org/wiki/Thos.](https://en.wiktionary.org/wiki/Thos.)
> semanticate: Add abbreviation for Thos.

- se/data/words
https://www.merriam-webster.com/dictionary/sailless
> modernize-spelling: Add sail-less -> sailless

- se/data/words
We had resell but not resold.
https://www.merriam-webster.com/dictionary/resold
> modernize-spelling: Add re-sold -> resold

- se/se_epub_lint.py
See manual PR https://github.com/standardebooks/manual/pull/11
> Add AC and DC as exceptions to abbr initialism rule t-030

- se/spelling.py
Currently phantasies modernises to fantasys.
> Phantasies -> fantasies

- se/spelling.py
We already have disburthen -> disburden.
Present in the corpus at:
- https://github.com/standardebooks/h-g-wells_short-fiction/blob/48c6ce586ea929ed5529d4f7556d70e6b7d0046e/src/epub/text/a-story-of-the-days-to-come.xhtml#L679
- https://github.com/standardebooks/h-p-lovecraft_short-fiction/blob/433246b0ffe20499934ade4e76f4748265716fa7/src/epub/text/a-reminiscence-of-dr-samuel-johnson.xhtml#L15
- https://github.com/standardebooks/thomas-de-quincey_suspiria-de-profundis/blob/3db7738e6f44f351538b56ca7261b3014d024f89/src/epub/text/the-affliction-of-childhood.xhtml#L12
> unburthen -> unburden

- .github/workflows/se-test.yml
Explicitly set pipx environment variables so that paths don't
change unexpectedly.
Fixes #366.
> Fix pipx environment

- se/typography.py
- setup.py
Discussion in https://github.com/standardebooks/tools/issues/373.
> Switch PyHyphen out for pyphen

- se/spelling.py
We’re currently only modernising the English pluralisation, but not the French.
> chateaux -> châteaux

- se/data/words
https://www.merriam-webster.com/dictionary/bedsheet
> bed-sheet -> bedsheet

- se/data/words
- se/spelling.py
https://www.merriam-webster.com/dictionary/spiderweb
> Some spelling modernizations

- se/data/words
https://www.merriam-webster.com/dictionary/hatstand
> hat-stand -> hatstand

- se/data/words
https://www.merriam-webster.com/dictionary/pinprick
Different tenses of the verb "pinprick"
> Add pinpricked, pinpricking to words

- se/se_epub.py
> Add dramatis-personae and halftitlepage to exluded files

- se/data/words
https://www.merriam-webster.com/dictionary/reestablish
> re-establishment -> reestablishment

- se/commands/create_draft.py
- tests/data/formatting/in/meta.xhtml
- tests/data/formatting/out/meta.xhtml
Fixes https://github.com/standardebooks/tools/issues/427.
> Add David Widger’s LCCN ref in create-draft

- se/data/words
https://www.merriam-webster.com/dictionary/deadweight
> modernize-spelling: Add dead-weight -> deadweight

- se/data/words
https://www.merriam-webster.com/dictionary/aplenty
> modernize-spelling: Add a-plenty -> aplenty

- se/data/words
https://www.merriam-webster.com/dictionary/outrace
> modernize-spelling: Add out-race -> outrace

- se/data/words
https://www.merriam-webster.com/dictionary/birdlike
> bird-like -> birdlike

- se/se_epub.py
I took a quick look at lunch and eliminating the outer try/except in your changes for the missing container.xml also made the ToC message work, so thanks very much!
There's a typo in the container message, and I added the clarification I mentioned on the list, just in case it really is a missing container.xml that's the problem instead of not being in an SE directory.
> Fix typo, add clarifying comment

- se/data/words
https://www.merriam-webster.com/dictionary/lifeboatmen
> lifeboat-man -> lifeboatman

- pylintrc
- se/images.py
- se/se_epub.py
- se/se_epub_build.py
- se/se_epub_lint.py
This gets us back up to zero lint errors.
> Fix linting errors

- se/data/words
https://www.merriam-webster.com/dictionary/rockfall
> rock-fall -> rockfall

- se/se_epub.py
Addresses issue #452 . I'm not sure this is the best way to do it, but I'm now looking for missing endnotes and duplicate endnotes BEFORE we do the renumbering process. I think what happened when I lost data is that I hit an exception AFTER already having renumbered some of the endnotes in the body of the text. Crashing out part way is not a good thing!
> Added safety check before running renumber-endnotes

- se/data/words
https://www.merriam-webster.com/dictionary/ashpan
> ash-pan -> ashpan

- se/commands/create_draft.py
While I was waiting I went a head and did a PR re #466. I just assigned `output` to the raw `pg_ebook_html` if the parse failed and moved the write outside of the existing `try` to its own `try`. I also adjusted the error message to say the test was saved, and fixed a couple of minor typos while I was in the area.
I had a heck of a time testing; the PG id that generated this started working all of a sudden. It took me a little while to figure out that the change Mike made on 7/25 re encoding actually fixed the problem with this particular id. I had to revert his change temporarily so I could test.
> Save body text even if it can't be parsed

- se/data/words
https://www.merriam-webster.com/dictionary/outclimb
> modernize-spelling: out-climb -> outclimb

- se/data/words
https://www.merriam-webster.com/dictionary/unrevolutionary
> un-revolutionary -> unrevolutionary

- se/data/words
https://www.merriam-webster.com/dictionary/peacemaking
https://www.merriam-webster.com/dictionary/thousandfold
> modernize-spelling: peace-making -> peacemaking and thousand-fold -> thousandfold

- se/data/words
https://www.merriam-webster.com/dictionary/sweetgrass
> modernize-spelling: sweet-grass -> sweetgrass

- se/se_epub_build.py
So, more out of interest that anything else, I hacked together this commit, built Beatrix Potter kepub again, and got this result:
Those are native SVGs, running directly in the renderer. I’m not sure why we haven’t done this historically, so maybe this is a more recent addition? But it seems to work without trouble. Admittedly I haven’t yet tried it on other books.
> Remove SVG -> PNG conversion for Kobo

- se/se_epub_build.py
I am following the same testing procedure I used [for the original koboSpan poetry fix](https://github.com/standardebooks/tools/pull/511#issuecomment-1106642110). Tests on *The Wind in the Willows*, de Cleyre, and Newman since those surfaced the issues in the first place.
```
wcheng@pop-os:~/git/kenneth-grahame_the-wind-in-the-willows$ se compare-versions .
```
```
wcheng@pop-os:~/git/voltairine-de-cleyre_poetry$ se compare-versions .
Difference in endnotes.xhtml
```
```
wcheng@pop-os:~/git/john-henry-newman_verses-on-various-occasions$ se compare-versions .
Difference in endnotes.xhtml
```
The differences in endnotes.xhtml are expected, having to do with the different endnote backlink character for Kobo vs. compatible, and image rendering differences for the sheet music in Newman.
I also …
> build: Fix koboSpan CSS conflict issue

- se/spelling.py
According to MW this is ”chiefly British”, and there are a few occurrences across the corpus.
> modernize-spelling: fœtus -> foetus

- se/se_epub_lint.py
I came across these loan words that were italicized in The Bostonians by Henry James.
> lint: Add more loan words to to-043

- se/commands/create_draft.py
This seems to work well enough, at least for a few of the names listed in https://github.com/standardebooks/anonymous_the-nibelungenlied_alice-horton/pull/1#issue-1528606433.
Resolves https://github.com/standardebooks/tools/issues/557.
(In other news, our runners will no longer check PRs due to 18.04 being removed yesterday: https://github.com/actions/runner-images/issues/6002.)
> If an LCSH Subject isn’t found, attempt to find in the Names authority

- se/data/words
We have ”doglike” already, and I’ve seen both used in a single sentence to contrast characters.
> Add “catlike” to the words list

- se/se_epub_generate_toc.py
This (at last!) is my fix for the crash in build-toc encountered by Robert Dixon in "Tom Brown's Schooldays"
https://groups.google.com/g/standardebooks/c/TN5N_lvy3eQ/m/xeyVWHSHJwAJ
> Fix to prevent crash in build-toc due to no content item on page

- se/spelling.py
> modernize-spelling: under weigh -> underway

- README.md
replaces dashes `-` with underscores `_` and formatted with spaces and new lines to make it easier for reading
> improved text representation of the directory structure

- se/spelling.py
Should catch dépôt now, in addition to depôt
> modernize-spelling: Catch depot with variation of diacritic

- se/spelling.py
If we take this then I’ll update:
- sun-tzu_the-art-of-war_lionel-giles
- joseph-furphy_such-is-life
- anthony-trollope_the-claverings
> Modernize bonâ fide to bona fide

- se/data/words
https://www.merriam-webster.com/dictionary/nongovernmental
> modernize-spelling: non-governmental -> nongovernmental

- se/data/words
https://www.merriam-webster.com/dictionary/upbuild
> modernize-spelling: Add upbuild, upbuilt, upbuilding

- se/commands/find_unusual_characters.py
Fixes https://github.com/standardebooks/tools/issues/617.
> Add better documentation for how the unusual characters regex is built

- se/se_epub_lint.py
Fixes #637.
Tested with good and bad files, only bad ones reported.
> Add back f-015 lint test accidentally lost during restructuring

- se/data/words
https://www.merriam-webster.com/dictionary/forerun
> modernize-spelling: fore-ran -> foreran, fore-run -> forerun, fore-running -> forerunning

- se/se_epub_lint.py
Per discussion. After this is merged I'll add a lint ignore file to _Ten Days That Shook the World_ and fix the other errors this found; there were less than a handful.
> Look for uppercase as well in y-012

- se/se_epub_lint.py
- tests/lint/typos/y-007/golden/y-007-out.txt
- tests/lint/typos/y-007/in/src/epub/text/chapter-1.xhtml
> Remove y-021, reference to it in y-007 test

- se/se_epub_lint.py
> Improve t-041, add period to list of checked punctuation

- se/se_epub_lint.py
- tests/lint/typos/y-026/golden/y-026-out.txt
- tests/lint/typos/y-026/in/src/epub/text/chapter-1.xhtml
- tests/lint/typos/y-027/golden/y-027-out.txt
- tests/lint/typos/y-027/in/src/epub/text/chapter-1.xhtml
- tests/lint/typos/y-028/golden/y-028-out.txt
- tests/lint/typos/y-028/in/src/epub/text/chapter-1.xhtml
- tests/lint/typos/y-029/golden/y-029-out.txt
- tests/lint/typos/y-029/in/src/epub/text/chapter-1.xhtml
- tests/lint/typos/y-030/golden/y-030-out.txt
- tests/lint/typos/y-030/in/src/epub/text/chapter-1.xhtml
Also updated the comment on y-028 to include the exclusion of plurals (were excluded but not mentioned in the comment before).
> Add lint tests y-026 thru y-030

- se/easy_xml.py
Instead of replacing them after the fact.
https://lxml.de/xpathxslt.html#xpath-return-values
> Disable smart_strings in XPath results

- se/se_epub_generate_toc.py
- se/se_epub_lint.py
- tests/lint/semantic/s-001/golden/s-001-out.txt
- tests/lint/semantic/s-001/in/src/epub/text/chapter-1.xhtml
> Include matches in s-001 lint messages and remove unnecessary findalls

- se/se_epub_lint.py
- tests/lint/semantic/s-041/golden/s-041-out.txt
- tests/lint/semantic/s-041/in/src/epub/content.opf
- tests/lint/semantic/s-041/in/src/epub/text/chapter-1.xhtml
- tests/lint/semantic/s-041/in/src/epub/text/colophon.xhtml
- tests/lint/semantic/s-041/in/src/epub/text/loi.xhtml
And reword the corresponding lint message to indicate that alt is allowed.
> Fix check for LoI text against either figcaption or alt text in s-041

- se/commands/typogrify.py
- tests/draft_commands/typogrify/test-1/golden/typogrify.xhtml
- tests/draft_commands/typogrify/test-1/in/typogrify.xhtml
> Typogrify alt attributes in images when a DOM can be parsed

- se/data/words
> Add fleshpot(s) to hyphenation word list

- se/data/words
> Remove hardhearted[ness] from hyphenated words list

- se/data/words
In M-W. There are a handful of vine-dresser(s) in the corpus; I'll start working on them if this is approved.
> Add vinedresser(s) to hyphenation word list

- se/data/words
https://www.merriam-webster.com/dictionary/woodchopper
> modernize-spelling: wood-chopper -> woodchopper

- README.md
This PR updates the documentation for installing the tooling on macOS.
> Update macOS documentation

- se/data/words
These are all in M-W, a couple (e.g. midmorning) in unabridged and one (leechcraft) in medical.
We have a large quantity of some of these (e.g. 89 pine-wood, 45 spring-tide), so it will take a while to get them all corrected.
(All of these are real-world, i.e. came from a production I'm reviewing.)
anigh
bowshot(s)
erewhile
leechcraft
mayhappen
midmorning(s)
missay
naysay
neatherd(s)
pinewood(s)
springtide(s)
wherethrough
wildwood(s)
woodside
> Add several words to hyphenated word list

- se/data/words
bloodlust
innyard
rushlight
teaboard
> Add more words to hyphenated word list

- se/data/words
bellpull
bellpulls
bloodred
cardplayer
cardplayers
cardroom
cardrooms
cherrywood
firstfruits
millhouse
millhouses
pastepot
pastepots
pastrycook
pastrycooks
playactor
playactors
postboy
postboys
posthaste
ragpickers
sansculotte
sansculottish
sansculottism
sansculottes
shopgirl
shopgirls
silklined
streetlamp
streetlamps
trapdoor
trapdoors
wastepaper
wastepapers
workgirl
workgirls
> Add a number of words to the hyphenated words list

- se/se_epub_lint.py
- tests/lint/metadata/m-080/golden/m-080-out.txt
- tests/lint/metadata/m-080/in/src/epub/content.opf
- tests/lint/metadata/m-080/in/src/epub/text/colophon.xhtml
We use Faded Page enough to check this, I think.
> lint: Add m-080 check for PGDP Canada name

- se/se_epub_lint.py
Sometimes I make myself tired… (I know, I make other people tired even more often…)
> lint: Fix m-080 test

- se/commands/create_draft.py
> Improve create_draft handling of transcribers

- se/se_epub_lint.py
Add a couple of letter semantics that weren't being tested for in s-076.
> lint: Improve s-076

- README.md
> New instructions for macOS (Homebrew)

- se/easy_xml.py
- se/se_epub.py
- se/se_epub_lint.py
- tests/lint/typography/t-010/golden/t-010-out.txt
- tests/lint/typography/t-063/golden/t-063-out.txt
- tests/lint/typography/t-063/in/src/epub/text/chapter-1.xhtml
- tests/lint/typos/y-001/golden/y-001-out.txt
- tests/lint/typos/y-030/golden/y-030-out.txt
Covers the majority of the non-CSS errors in #858. Everything here is checked off on that list. The CSS and other remaining errors will take a bit more effort to implement. Not sure when I'll have time to do that, so opening this PR.
> lint: Line numbers round two

- tests/string_commands/make-url-safe
Add some tests for leading/trailing dashes in make-url-safe.
> Update make-url-safe test with quoted strings
