modernize-spelling
‘waggon’ [listed as ‘dated’ on wiktionary](https://en.wiktionary.org/wiki/waggon), and feels wrong to me. Came up a couple of times in Gogol’s Dead Souls.
=> Add waggon -> wagon

build
Show a message if `ebook-convert` fails in verbose mode. Otherwise, the command prompt is appended to the end of the *Building %s ..." "${kindleOutputFilename}"* line.
=> ebook-convert failed message

split-file
split-files doesn't create a file for the last segment (after the last ``). This update changes this so you don't need a split at the end of the file.
=> fix split-files so it doesn't drop last segment

README.md, build, prepare-release
This is ready for review now:
- modified `build` script to run on macOS.
- modified `prepare-release` script to run on macOS. 
- modified README to include macOS setup instructions.
Tested on macOS 10.12.5 and Ubuntu 16.04.2 LTS
Note: Hyphenation doesn't work, but it doesn't work on Ubuntu either so I don't think it has anything to do with running on a Mac. It looks like pyhyphen is just broken.
=> Improve macOS support

british2american
Attempts to detect quote style used in a file, by separately counting matches for left-double-quote and left-single-quote, after a `<p>` tag on the same line, and comparing the percentage of each. If percentage is above a threshold (80%), a detection is found and returned, otherwise, 'unsure' is returned.
If 'British' quote style is detected, file conversion continues unprompted.
If 'American' quote style is detected, or detection is unsure, user is prompted before continuing with file conversion (defaults to No).
Quote detection can be skipped entirely by passing a `-f` or `--force` flag, and conversion will continue unprompted (old behaviour).
Fixes #18.
=> Detect quote style when running british2american

README.md
I've made a few tweaks to the readme based on testing the new python version:
1. Switched to using homebrew to install java and calibre
2. Switch inkscape to use standard hombrew cask version (turns out cask is standard now)
3. Add exiftool install
=> fixup readme for macos

build
1. When the default encoding is ascii build fails in a couple places; added explicit encoding
2. The kindle endnotes conversion fails because of a variable name mismatch; fixed
Note: I'm a python noob. Please review.
=> Fix for encoding issues when default encoding is ASCII; kindle endnotes error

README.md
The stock Ubuntu installation image (presently 16.04.3) does not include curl or git, which are required in step 2 of the installation.  I have added them to the initial dependency list.
=> Add curl and git to dependency list for Ubuntu 16.04

se/se_epub.py
This collects text from the headings that has had the tags stripped and whitespace normalised. It then checks them off against the ToC entries to see if any are present that don’t have an entry.
The only amend we do to the ToC entries is to strip out the `:` that the style guide suggests for after the chapter number.
Problems found so far:
- Missing entries! Nice to see it works. E.g. [missing chapter 5 entry](https://github.com/standardebooks/arthur-machen_short-fiction/blob/6d14f29a42dbb41ca4fe7c58ab26aacdec5eb9d9/src/epub/toc.xhtml#L60) from [`the-inmost-light.xhtml`](https://github.com/standardebooks/arthur-machen_short-fiction/blob/6d14f29a42dbb41ca4fe7c58ab26aacdec5eb9d9/src/epub/text/the-inmost-light.xhtml#L126) in Arthur Machen, missing …
=> Lint for headings in text that aren’t in the ToC

se/se_epub.py
The existing code pulls the heading text out of a text/filename tuple and checks it against the ToC. If we add the expected filename to the ToC entry as a tuple (from the entry’s href attribute) then we can compare tuples rather than text strings.
This addresses this comment in the previous PR: https://github.com/standardebooks/tools/pull/48#issuecomment-340328314
I don’t have the full corpus on this laptop but I’ve cloned Crime & Punishment, edited `chapter-5-5.xhtml`’s heading to be `VI` and this is caught with this PR, even though `VI` exists as a heading in other parts.
=> Teach ToC heading linting about files

se/formatting.py, se/se_epub.py
This does two things:
1. Teaches `titlecase` that a letter immediately following a `‘`, `“` or an `<i>` with an attribute that starts `se:` shoud be uppercase.
2. Adjusts the linting to apply `titlecase` first before stripping tags to make sure there’s no disparity between the linter and the real world.
Fixes https://github.com/standardebooks/tools/issues/50. I think this works OK, been testing with Keats and it seems to, although I’ve been down a couple of blind alleys on the way to this solution.
=> Make titlecase linting aware of embedded titles

se/se_epub.py
This is based on the algorithm suggested in https://github.com/standardebooks/tools/pull/48#issuecomment-346490298. It has the added bonus of simplifying the code a bit, although it’s still complex enough that I detailed the process in a comment above.
I’ve tested this manually with a few different configurations and it seems to work, but I haven’t run it over the full corpus.
=> New algorithm for subtitle inclusion in the ToC

se/se_epub.py
I got an error running lint under macOS 10.12.:
```
Traceback (most recent call last):
File "../tools/lint", line 61, in <module>
main()
File "../tools/lint", line 25, in main
messages = se_epub.lint()
File "/Users/steve/Documents/StandardEbooks/tools/se/se_epub.py", line 451, in lint
expected_manifest = regex.sub(r"[\n\t]", "", self.generate_manifest())
File "/Users/steve/Documents/StandardEbooks/tools/se/se_epub.py", line 282, in generate_manifest
file_contents = file.read()
File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/codecs.py", line 321, in decode
(result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 3131: invalid start byte
```
It was trying to process …
=> Lint tries to process .DS_Store on macOS

modernize-spelling
Seems equivalent to indorse -> endorse
=> modernize-spelling: Add intrust -> entrust

reorder-endnotes
In the new endnote style the links to the notes have an `id` attribute starting with `noteref-`, but the existing code is still looking for `note-`.
Obviously this commit will break reordering endnotes in the old style, so if older books have endnotes added they’ll need to be updated to the new style first.
=> Fix endnote reordering

modernize-spelling
This simply lowercases the right side before concatting it. Potentially there are some words that it will fail on, but I can’t think of any and spelling changes should be manually reviewed anyway.
Test case (from Moby Dick): with this patch `Free-Mason` becomes `Freemason`, not `FreeMason`.
Fixes https://github.com/standardebooks/tools/issues/68.
=> Hyphen removal shouldn’t leave capitals in the middle of words

create-draft, templates/content.opf
- Fix an extra space in `content.opf`
- Insert a blank newline at the end of `cover.svg` and `titlepage.svg` (via method given at https://stackoverflow.com/a/31906126/453783)
After this the only error `clean` fixes on a newly created SE repo is removing the `CDATA` blocks around the long description. I assume this is expected so have left it as is.
=> Minimise default clean fixes

create-draft, requirements.txt
I’ve noticed on a couple of recent books that `create-draft`’s automatic Gutenberg pull fails to properly encode characters in the HTML. For example, this command:
`~/tools/create-draft --author="Selma Lagerlöf" --title="The Story of Gösta Berling" --translator="Pauline Bancroft Flach" --gutenberg-ebook-url="https://www.gutenberg.org/ebooks/56158"`
will produce a body.xhtml with a title of `The Story of GÃ¶sta Berling`, not `The Story of Gösta Berling` due to requests assuming the file is ISO-8859-1 encoded. requests will try to guess an appropriate encoding but this particular file (and others I’ve tried) don’t supply an encoding value in the headers. As we always want UTF-8 anyway we can just tell requests to use the correct encoding.
It’s possible this will break some files, but files …
=> Force utf-8 when creating a draft

README.md
Pip works for py2 which is incompatible with some packages such as ftfy. Pip3 adresses the problem
=> Update to Mac instructions

se/se_epub.py
Add a spine check to the ToC section of the linter. Previously we were getting all ToC entries with `find_all('a')` but we need them depth first to match the spine order. This first changes the heading selection order to be in (hopefully) spine order, then checks each against the corresponding spine entry for a match. If it fails it throws an single failing error for the whole spine and breaks out.
Fixes https://github.com/standardebooks/tools/issues/86.
=> Check the spine’s order against the ToC order

se/se_epub.py
The title text in the SVG should always match the alt text in the associated figure, so that’s easy to lint and error on (if there’s no title, eg a PNG we can bail). As well as that, the title text should mostly match the text in the LoI but there are cases where this doesn’t work (eg Just So Stories), so if it doesn’t we emit a manual review warning.
=> Make sure LoI text / image title / figure alt text are consistent

se/se_epub.py
A warning and not an error as it’s possible (e.g. Just So Stories) for figcaptions to differ significantly from LoI text on purpose, although this generally isn’t the case. This also removes the warning that matched SVG `<title>`s against LoI text as that turned out to be problematic.
=> Add a warning if figcaption doesn’t match LoI text

modernize-spelling
Regex was looking for a literal ‘sd’ string rather than one of the two characters.
=> Fix fêtes/fêted replacement

se/se_epub.py
The removes the alt / title match checking from the LoI section and applies it to every referenced .svg.
Unfortunately though this has exposed a problem: the title tag in titlepage.svg (default `The titlepage for the Standard Ebooks edition of TITLESTRING`) doesn’t match the alt text in titlepage.xhtml (default `TITLESTRING`). The obvious two fixes that spring to mind are to normalise the title / alt strings in this case and republish every book, or to ignore the titlepage in another commit to this PR before merging. I’d be happy with either, but I’ll leave it up to you to make the decision.
=> Make sure alt text / image title match checking is run against all images

se/se_epub.py
The lowercase title check errors if it detects an amp entity. While this will potentially throw a false positive if the &amp; is surrounded by other lowercase text this should be easily picked up on review anyway.
=> Don’t error on ampersands in title SVG

se/se_epub.py
ToC headings often have colons added (e.g. XX: Chapter 20). During the linting we strip these so that we can compare the ToC headings and the real headings. Unfortunately we sometimes have real headings that have colons embedded (for example T. S. Eliot’s poem ‘Burbank with a Baedeker: Bleistein with a Cigar’).
We can work around this by temporarily stripping all colons from chapter headings before comparing them to the ToC heading.
I ran this against the corpus and it fixes the reported issue in https://github.com/standardebooks/tools/issues/99 without any side-effects that I could see. The obvious problem is that now there could potentially be misplaced colons that wouldn’t be picked up by linting, but I’m not sure how to work around that.
=> Cope with headings with colons while linting

se/__init__.py
The replace code wasn’t assigning to the variable that was later written back into the file. Obvious once you see it 🙂
=> Fix create-draft failing to insert text in specific places

clean
This PR fixes #107. I tested with valid and invalid references of all three types, and the code works as intended — with one exception. If you give it a really huge (which implies invalid) numerical character reference, it will throw an `OverflowError`. I can handle that too, but I'm not sure if it's necessary.
=> Don’t replace &gt; and &lt;

requirements.txt
clang 9.1.0 throws a bunch of errors around nulls when trying to compile lxml 3.8.0. lxml 4.2.3 (current at time of patch) doesn’t seem to fundamentally change any functionality we’re relying on, promises speed ups, and more importantly compiles fine.
=> Fix lxml 3.8.0 failing to compile on default 10.13 macOS

se/se_epub.py
If, in the same line, there was an seperate occurence of -0[0-9] then the test would fail, even though the id was correct. This fix is to scope the regex to only look for characters that are inside the quote marks.
For reference, a failing line from U S Grant’s memoirs:
`<p>On the <time datetime="1865-04-08">8th</time> I had followed the Army of the Potomac in rear of Lee. I was suffering very severely with a sick headache,<a href="../text/endnotes.xhtml#note-43" id="noteref-43" epub:type="noteref">43</a> and stopped at a farmhouse on the road some distance in rear of the main body of the army. I spent the night in bathing my feet in hot water and mustard, and putting mustard plasters on my wrists and the back part of my neck, hoping to be cured by morning. During the night I received …
=> Fix regex in broken leading zero test

README.md, build, hyphenate, requirements.txt
This fixes installation problems on macOS (tested on 10.13), and changes the way dict_info is accessed to match the new 3.0 way.
Installation succeeds, and en-GB libraries are downloaded automatically where needed. Running hyphenate manually against a chapter produces a soft-hyphenated file, and build --kindle produces an azw3 file without complaint.
Untested on Linux or older macOS. The changelog between the old 2.0.8 and the new 3.0.1 is at https://pypi.org/project/PyHyphen/#changelog.
=> Upgrade Pyhyphen

README.md
without this, you get the following error:
```
$ tools/extract-ebook --help
Traceback (most recent call last):
File "tools/extract-ebook", line 8, in <module>
import magic
File "/Users/alsuren/envs/standardebooks/lib/python3.7/site-packages/magic.py", line 176, in <module>
raise ImportError('failed to find libmagic.  Check your installation')
ImportError: failed to find libmagic.  Check your installation
```
=> brew install libmagic

reorder-endnotes
This PR drops endnote reordering (increment all endnotes from 1, against current Pepys with 1595 endnotes) from ~23.5s to 5s on my laptop, and adds in the ability to reorder links inside `endnotes.xhtml` to other endnotes assuming they are of the form `<a href="#note-x">note x</a>` or close.
The speed-up comes from reworking the existing regex sub inside the loop to be a straight text replacement. Python should cache regular expressions as they’re first evaluated, but it turns out that generating and caching ~1600 of them is pretty slow.
=> Speed up endnote reordering again, and make it more correct

create-draft
This pull request addresses the strange formatting issue [reported on the mailing list](https://groups.google.com/forum/#!topic/standardebooks/VkRe8FA9tl0):
> Not sure what the problem is, but after running `create-draft` with
> 
>  `   ~/tools/create-draft --author="William Beckford" --title="Vathek: An Arabian Tale" --gutenberg-ebook-url="https://www.gutenberg.org/ebooks/42401"`
> 
> src/epub/text/body.xhtml looks like this -
> 
> `    ...
<p>The last years of his life were passed at Bath—where he united two houses in Lansdown Crescent, by an arch thrown across the street, and containing his library, which was well selected, and very extensive. Not far off, he again erected a tower, 180 feet high, of which the following d e s c r i p t i o n w a s g i v e n a t t h e t i m e o f h i s d …
=> Replace lxml with html.parser when fetching ebook html

se/data/templates/compatibility.css
I’m not sure if this is a new theme, but if you put macOS into ‘dark mode’ Apple Books (née iBooks) defaults to a grey theme. The illustrations also need to be flipped here. Screenshots:
Before:
After:
Incidentally, Apple has added an experimental [`prefers-color-scheme: dark`](https://blog.iconfactory.com/2018/10/dark-mode-and-css/) media query to Safari which I imagine will come to Books at some point and could replace these app specific selections. That’s a future thing though.
=> Flip b+w illustrations in Apple Books grey theme

se/spelling.py
We were accidentally just moderising ‘bowlder’ and not ‘bowlders’ which is a pretty common variant.
=> Modernise plural of boulder as well

se/se_epub.py
Would it be possible to make this small change to recompose-epub? It would make life easier for me to use its output if I could make a call to it and have it omit the ToC in its return string.
=> Made adding ToC to recompose-epub optional, on by default

se/__init__.py, setup.py
This enables the tools to be installed without needing to install
dependencies in a separate step.  It follows the same pattern as the
popular trio Python library.
=> Move version specification out of __init__.py.

se/se_epub_lint.py
Suggested improvement: tell the producer what doesn't match in the spine order.
Now outputs, as example:
Error: content.opf The spine order does not match the order of the ToC and landmarks. Expected part-1.xhtml, found chapter-1-1.xhtml
=> Expanded lint message about ToC not matching spine order.

se/se_epub_generate_toc.py
I think I've fixed this particular issue. I can't think of any other tags than `<abbr>` or `<i>` which could appear in titles or subtitles, can you? `<em>` and `<b>` and `<strong>` shouldn't be in there, but should I handle these, too?
`<span>` for noterefs is already handled.
=> Fixed bug with italicised items in titles or subtitles

se/se_epub_generate_toc.py
Addresses issue #142.
My bad. I didn't test my previous method of obtaining the se:subject values, which was way wrong. Copied your approach in lint.
=> Fixed incorrect method of determining fiction/non-fiction status

se/se_epub_generate_toc.py
Addresses #144. On reflection, the appropriate action here is not to raise an exception but simply not to add the file as a landmark.
=> Removed raising error if epub:type not found when adding landmarks.

se/se_epub_generate_toc.py
I'm now removing noterefs as soon as I've read in the html for each file. This has enabled a considerable simplification of code further downstream (see extract_strings, for example).
=> Simplified removal of noterefs and removed code handling these

se/se_epub_generate_toc.py
I think this is now as close as I can get it to completion. Mismatches found when running over the entire corpus are either:
1. Inclusion of subtitles for Parts and Divisions
2. Inclusion of `<abbr>` or `<i>` tags in Toc
3. Files with unique structures like Keat's poetry
Just as a note: the routine to apply print-toc over the entire corpus and check for mismatches runs in just over 2 minutes, which I reckon is pretty good.
=> Fixes to issues found when running print-toc over corpus

se/se_epub_generate_toc.py
Addresses issue #155 . However, it's not quite as simple a fix as it looks. In short fiction collections sections are given an epub:type of  "volume se:short-story". I've never quite understood that, tbh. Anyway, I'm filtering out such epub:types as it could give us subtitles to short stories in the ToC, which I presume we don't want.
=> Now including subtitles for Volume divisions

se/spelling.py
Google Ngrams: https://books.google.com/ngrams/graph?content=impale%2Cempale&year_start=1800&year_end=2000&corpus=15&smoothing=3&share=&direct_url=t1%3B%2Cimpale%3B%2Cc0%3B.t1%3B%2Cempale%3B%2Cc0
"empaled" was used in *Commentaries on the Gallic War*, and we're changing it to "impaled".
=> Add empale -> impale to modernize-spelling

se/spelling.py
This issue was consistent throughout "Such is Life", and I think I've seen it once or twice before:
do n't -> don't
is n't -> isn't
So I think it's worth adding to modernize-spelling.
=> Added regex to spelling for space before contraction n't

se/se_epub_lint.py
If you have run `se create-draft` and then run `se lint` but have not run `se build-images` you get an exception that complains about `src/epub/images/titlepage.svg` being non-existent.
This commit catches the `FileNotFoundException` and reports a lint error message instead.
=> lint dies on non-existing referenced images

se/se_epub_lint.py
Don't know how I managed but I had different lengths in spine and ToC and so lint died with a IndexError.
This is how spine and ToC looked like, note the double `copyright.xhtml`.
```
['titlepage.xhtml', 'imprint.xhtml', 'body.xhtml', 'copyright.xhtml', 'endnotes.xhtml', 'loi.xhtml', 'colophon.xhtml']
<itemref idref="titlepage.xhtml"></itemref>
<itemref idref="imprint.xhtml"></itemref>
<itemref idref="body.xhtml"></itemref>
<itemref idref="copyright.xhtml"></itemref>
<itemref idref="endnotes.xhtml"></itemref>
<itemref idref="loi.xhtml"></itemref>
<itemref idref="colophon.xhtml"></itemref>
<itemref idref="copyright.xhtml"></itemref>
```
Please note that this happened on a modified version. To my knowledge none of the modifications should cause this. I think it doesn't hurt to check the …
=> check if lengths of spine and ToC match before comparing them

README.md
Developed install instructions for Fedora. Tested on Fedora 29. Should be compatible with 28/29/30.
=> Add install instructions for Fedora users

se/executables.py
When an unsupported language is detected, print the error message from the exception rather than using the (incorrect) hard-coded error message.
=> Replace obsolete error message

se/executables.py
The british2american command crashes if the text already uses american-style quotes. The crash is because the warning message is trying to print a Path object without converting it to a string.
$ se british2american .
Traceback (most recent call last):
File "/home/dave/work/se-tools/venv/bin/se", line 11, in <module>
load_entry_point('standardebooks', 'console_scripts', 'se')()
File "/home/dave/work/se-tools/se/executables.py", line 76, in main
return globals()[args.command.replace("-", "_")]()
File "/home/dave/work/se-tools/se/executables.py", line 103, in british2american
se.print_warning("File appears to already use American quote style, ignoring. Use --force to convert anyway.{}".format(" File: " + filename if not args.verbose else ""), args.verbose)
TypeError: must be str, not …
=> Convert Path to string before printing

se/executables_create_draft.py, se/mobi.py, se/se_epub.py
I've been playing around with running pylint on the standardebooks code and found these unused imports.
=> Remove unused imports

se/executables_create_draft.py
I was finding that the clean command was failing on the content.opf file. The root cause was an invalid (unescaped) URL for Wikipedia.
The URL "https://en.wikipedia.org/wiki/Special:Search?search=unknown_search_term&go=Go" was redirecting to "https://en.wikipedia.org/wiki/Special:Search?search=unknown_search_term&go=Go&ns0=1" (note extra ns0=1 term) which was then returned as a successful article match. The unescaped ampersands cause the clean on content.opf to fail.
I've updated the code with the new Wikipedia search URL. I also added a check to see if the URL path has actually updated to protect from future Wikipedia search parameter changes.
It might also be a good idea to html.escape() the URL? I can add that too if you think it's a good idea.
=> Update search URL for Wikipedia

setup.py
This gets us up to the latest on a bunch of packages. Rebuilding the entire corpus and MD5ing the `.epub` shows that pretty much all have changed, but checking specific packages (I tested with Wittgenstein, Babbage, and Johnson’s The Alchemist) shows that it’s the order of the generated pseudoclass classes versus the generated epub classes that’s causing the difference. No other differences were found.
Generally, the common themes for the updates were increased speed and dropping of Python 2 / 3.3. `ftfy` also claims that it should better detect mojibake in small words.
=> Package updates

se/se_epub_build.py
While trying to generate a `.azw3` file for Kindle, I got the output `Error: Couldn’t locate epubcheck. Is it installed?`
I felt this was a bit misleading as I did have `epubcheck` installed. The step was actually looking for `ebook-convert`, which ships as part of Calibre. I had forgot to install Calibre but spent a little bit of time scratching myself over why `se` couldn't find my `epubcheck` install.
I think you can possibly install `ebook-convert` as a standalone item but seeing as the docs recommend/require Calibre as an install step, it didn't seem that much of a stretch to have the error message just ask `Is Calibre installed?` rather than a potentially less informative `Is ebook-convert installed?`
=> Changed ebook-convert error message to be a bit clearer

se/data/templates/content.opf
There’s really nothing new in 2.1 that affects us (see https://www.w3.org/WAI/standards-guidelines/wcag/new-in-21/) but we might as well claim compliance with the latest version of the standard.
=> Update template to claim WCAG 2.1 compliance

se/__init__.py, se/se_epub_build.py, se/se_epub_lint.py
With this change, se tools print a more descriptive error message when cssselect encounters a CSS syntax error during lint or build.
Previously, the scripts simply exited with a stack trace that was difficult to decipher, and didn't indicate where in the CSS the problem was. This was reported in [this email](https://groups.google.com/d/msg/standardebooks/0CW04wKdKKE/S-gXUGW0DAAJ) on the mailing list.
This update allows se to exit with a clear error message that specifically says that there is a CSS problem and prints the text of the line where the problem was encountered, like this:
> Error: Couldn't parse CSS in or near this line: p[epub|type~"z3998:salutation"]
Limitations of this approach:
* The error doesn't say which file the error was in. Since SE projects should only be editing CSS …
=> Improve handling of CSS syntax errors

se/executables.py, se/se_epub.py, se/se_epub_generate_endnotes.py, se/se_epub_generate_toc.py
Alex: I think this now satisfies all the changes requested in your last email. I've tested it on Bulfinch (by removing a whole part) and it seems to work.
One question: the -verbose flag at the moment generates a fairly concise output:
`Found 76 endnotes.
Changed 4 endnotes
endnotes.xhtml recreated`
I have generated (internally) a MUCH more verbose report which lists each and every change made, but at present I'm not doing anything with it. With hundreds of endnotes it is a bit excessive, perhaps. Do we want a 'super-verbose' flag, or should I just include this in the verbose output anyway?
=> Added renumber-endnotes function and restructured se_epub

se/se_epub_lint.py
The manual says to have non-break spaces on either side of an ampersand. It's specifically talking about company names, but I can't think of a different situation where we would use ampersands and _not_ want the surround non-break spaces. If there is such a situation, then you can ignore this PR. :)
This adds lint checks for the nbsp's on either side of an ampersand.
=> Add check for nbsp's surrounding ampersands (&amp;)

se/se_epub_lint.py
Adds the same source checks to colophon that are on imprint. This catches instances where imprint and colophon have different sources, which I've accidentally done a couple of times.
Since colophon has the "digital scans available" on a separate line, ended with a ```<br/>```, then the URL on the next line, I chose to only check for the URL, rather than the entire ```the<br/>\s+<a …```. The regex wouldn't have been an issue (I don't think), but I couldn't come up with a good error message. And I was more worried about making sure the URL's were the same than that the "the" was present for Hathi and Internet Archive.
If you want the "the" checked for, just let me know what you'd like the error message to look like and I'll make the changes.
=> Add source checks to colophon

README.md
This turned out to be needed for a standard new Fedora install in a test VM, so that pipx could install standardebooks.
=> Add Python headers to required packages for Fedora

README.md
A recommendation to add to the toolkit for OpenBSD: the vim editor.  1) vim is required for `se interactive-vr`, 2) vimdiff can be configured for use with `git difftool`, nothing in the OpenBSD base or the tools list provides a utility for difftool, 3) gvim is useful for editing Unicode fields -- these cannot be easily edited with vim from a console/xterm -- and 4) the gtk3 infrastructure is already a dependency of calibre.
=> add vim--gtk3 to the OpenBSD tool set

se/se_epub_lint.py
Include the counts in the error message when the spine and TOC counts are off. Also report the first file mismatch even if the counts are off.
=> Provide more messaging for spine/TOC mismatches

se/vendor/kindleunpack/mobiml2xhtml.py
Some vendor code is not syntactically correct Python 3 code. This code is clearly not called anywhere, but these syntax errors generate unnecessary error reports from some tools (e.g. editors, pylint, mypy).
=> Fix syntax errors in vendor code

se/executables.py
The "se help" command uses globals() to get the command list, but the invalid "call" command was being included in the help output because it had been imported into the global namespace.
=> Remove subprocess.call() from global namespace

se/se_epub_lint.py
When there's an XML error in a file, lint just dies telling us the filename, but there is no indication what the error might be or where it is. In larger files (stories/chapters/etc.), it can take a while to find the problem. On the Mac, Quicklook will tell you the line/byte of the error, so this hasn't been a huge problem for me, but it would be a lot easier to get more detail direct from lint, and even more so for Windows/Linux.
This adds exceptions to the existing try/except for both encoding errors from the encode, and XML errors from lxml's etree. In a file where I was missing a closing quote on an epub:type, the error would look like this with the change. The "11:227" is the line and byte. (Without the closing quote, it searches the rest of the file for the closing bracket, thinking …
=> Report more details about encoding and XML errors

se/se_epub_generate_toc.py
The exception added to get_book_divison in TOC has no message, so the user just gets "Error:" when it occurs. This traps the error in the calling function and prints an informative message, including the filename. (No errors/warnings from pylint.)
=> Trap new exception from get_book_division and provide error message

README.md
Since pipx 0.15 the --spec flag has been removed. This new command worked for me to reinstall se.
=> Update pipx developer documentation

se/formatting.py
At the moment the roman numeral formatter only adds markup to standalone numbers, but this extends it to automatically mark up `Henry VIIIth` to be `Henry <span epub:type="z3998:roman">VIII</span>th`, for example.
=> Automatically mark up ordinal roman numerals

se/spelling.py
This is an editorial modernisation decision should part of spelling.
Tested in Tristram, leading to https://github.com/robinwhittleton/laurence-sterne_the-life-and-opinions-of-tristram-shandy-gentleman/commit/c4f18b41fa962b2e583986fb548a9e4de7610e7f.
=> Remove ordinals after roman numerals

se/se_epub_lint.py
The regex for this check looks for all caps surrounded by spaces, quotes, or angle brackets. This handles all of the colophon variables correctly and should also eliminate false positives of all-caps in other character sequences (e.g. Google Books links).
=> Improve error output for colophon lint check

pylintrc
I tried changing the code to move the imports. The performance penalty was just over 100 ms which seemed like a lot for the faster commands which run in around 500 ms on my machine. So in the end I just disabled the warning.
=> Disable import-outside-toplevel pylint error

README.md, se/se_epub.py
Bit of an ugly fix, but it seems to work on macOS at least, and hence fixes macOS 10.15’s inability to run the `build-images` script. My Fedora VM’s pipx env doesn’t seem to be automatically working with new code, but I’ve double-checked that the output of `inkscape --help` (with the default Inkscape 0.92.4 there) doesn’t include the `--export-file=` substring.
Thanks to @vr8hub for the hints that got me to a fix.
=> Fix the build-images script with Inkscape 1.0

se/executables.py, se/executables_create_draft.py
For testing the `create-draft` command it is better if it doesn't try to access external websites. The external access slows things down and may not even be possible in some test environments. This change adds an `--offline` option to the `create-draft` command that prevents it from making external requests to Gutenberg or Wikipedia.
=> Add offline option for create-draft command

se/se_epub.py
When running the `build-images` command without an X11 server (on Windows Subsystem for Linux), the calls to `inkscape` display some messages to stderr. These message are harmless but annoying so I have suppressed them. At the same time I have enabled the `subprocess.call()` check flag so that we catch any actual errors.
I also found that if the `DISPLAY` environment variable was set but the X11 server was not running, the `inkscape --help` command failed unless it also included the `--without-gui` option, so I have added it to the calls.
=> Hide stderr output for inkscape commands

se/formatting.py, se/se_epub_build.py
The old single-character fix: the regex used to detect the index wasn’t minimising and was selecting to the end of the last pseudoclass index.
=> Fix hang with multiple indexed pseudoclasses in a single selector

se/se_epub_build.py
Rather than doing regex manipulation to sort out the broken tree after unwrapping, we can just place the element in the place we want it before unwrapping it.
I never did find out what caused the bug in https://github.com/standardebooks/tools/issues/237 as this removes all the potentially buggy code.
Tested on Tristram Shandy, and Man and Wife. More testing appreciated before merging.
=> Simplify Kindle deep-ToC generation

pylintrc, se/commands/compare_versions.py, se/commands/dec2roman.py, se/commands/extract_ebook.py, se/commands/find_mismatched_diacritics.py, se/commands/lint.py, se/commands/roman2dec.py, se/commands/unicode_names.py, se/commands/version.py, se/se_epub.py
With the new file organization, we can move most imports to the top of their respective files and re-enable the pylint check.
=> Move imports to top level, enable pylint check

README.md
As referenced in https://github.com/standardebooks/tools/issues/188#issuecomment-589883518. I’ve tested this and it works fine.
=> Update README with recommended Mac pipx install method

se/data/templates/core.css, tests/data/draft/jane-austen_unknown-novel/src/epub/css/core.css
As mentioned in https://github.com/robinwhittleton/laurence-sterne_the-life-and-opinions-of-tristram-shandy-gentleman/issues/1. I’ll remove [the override](https://github.com/robinwhittleton/laurence-sterne_the-life-and-opinions-of-tristram-shandy-gentleman/blob/2e823f3f226739e9316b1ac6f405de89b059f1db/src/epub/css/local.css#L84-L86) from local.css in that project if this gets merged.
=> Guard against accidental italicisation of endnote references

.gitignore, se/__init__.py, se/commands/british2american.py, se/commands/modernize_spelling.py, se/commands/version.py, se/commands/word_count.py, se/se_epub.py, se/se_epub_build.py
So there didn't end up being that many if you don't count everything in se/vendor. It's passing the pylint and pytest tests. I didn't see how to set up the mypy tests in the readme.
I did end up leaving 7 instances of .format() in the code. Right now I think replacing these 7 wouldn't be worth the trouble. 
There are various reasons why f-strings are a pain for these. 5 of them are in regex strings, and because f-string doesn't always play nicely with quotes and escapes and things like that I thought I'd leave them. Also there's an example of nested .format() calls which I had trouble replacing, and one where the .format() call needs an escaped character, which you can't do in an f-string.
Here are my notes on the unchanged ones for future reference in case someone wants to tackle them …
=> manual f-string update

se/se_epub_build.py
Fixes https://github.com/standardebooks/tools/issues/276.
=> Use a normal arrow instead of a guillemet for Kobo endnotes

se/formatting.py
BS4 selection doesn’t seem to understand namespaced attribute selectors, so selecting based on `id` instead.
=> Remove endnotes from titles before printing them

README.md
I got a new mac for the first time in a long time, and after trying to build the book I’m working on got some errors. Tracked it down to a missing libcairo, which is installable with brew. I’m not sure if I just always had this on my old machine and hence never realised, or if it was part of macOS previously and has since been removed, but hey.
=> Add needed cairo to macOS install instructions

se/formatting.py
I’m not exactly sure what’s causing this, but without the added else statement, I’m getting concatenated latin/roman numbers on current production (for example `Chapter 23XXIII`). I can’t see any reason why we wouldn’t want the else statement, as we’ve definitely finished what we’re doing by this point.
=> Fix print-title with books with parts

se/commands/build_images.py
Command was throwing an exception if the user provided an invalid directory.
Moved the `SePub` init inside the try block so that an exception will print a nice error message. Also moved the `resolve()` statement so that the full directory name is displayed with `-v` option.
=> build-images: Fix exception for invalid source directory

se/se_epub_build.py
A CSSSelector object for a given CSS selector string is reusable. Reusing the object saves re-compiling the CSS into XPath, which is fairly compute intensive. On my sample build, the build time was reduced by about 2.5 seconds (for a 9 second build).
=> Cache CSSSelector instances to improve build performance

se/easy_xml.py, se/se_epub_build.py, se/se_epub_lint.py
I moved the cache to the `se.easy_xml` module because most of the `CSSSelector` creations for the lint command are happening in the `EasyXmlTree.css_select()` method. This change should also speed up the MathML processing in the build command because it was using `EasyXmlTree.css_select()` too.
=> Use CSSSelector cache for lint command

se/formatting.py
Previously failed with "IndexError: list index out of range" if the list returned from `regex.findall()` was empty.
=> clean: Avoid crash if long-description is missing from metadata

se/browser.py
It’s easier to just grab with with brew on macOS than to install it manually.
=> Add macOS installation instructions for geckodriver

se/browser.py, se/images.py, se/se_epub_build.py
Images can take a srcset attribute with hiDPI image options. We can tweak the Firefox webdriver to output this, then use pillow to provide a normal resolution version. Screenshots from macOS Apple Books:
Before:
After:
Only tested on macOS Books: the only other hardware I have available is Kobo and that has native MathML. I don’t see this being a compatibility issue though, the original `src` attribute is there for renderers that don’t support `srcset`.
=> Add hiDPI PNGs for pre-rendered MathML

se/se_epub_build.py
epubcheck is complaining about `@` symbols in ids in projects with MathML. The `@2x` style file naming is conventional in FE web dev, but it’s not required, so we can swap it out for an underscore instead with the same effect, but valid ids.
Sorry, should have run epubcheck before the previous PR.
=> Fix invalid ids in built content.opf with MathML

se/data/words
Don't know if we're manually updating this dictionary but I came across "hotel-keeper" which in Merriam-Webster (which we seem to be using for the most part) is written without the hyphen (https://www.merriam-webster.com/dictionary/hotelkeeper) so I decided to add it.
=> modernize-spelling: Add hotelkeeper

se/se_epub_lint.py
Longdesc should be valid HTML, not XHTML.
There were a single-digit number of occurrences of this in the corpus which I’ve fixed up.
=> Lint longdesc xmllang

se/data/words
Found whichever spelled "which-ever". https://www.merriam-webster.com/dictionary/whichever
=> modernize-spelling: Add whichever

se/formatting.py
Abbreviation for Gov. -> Governor. https://en.wiktionary.org/wiki/Gov. It's also sometimes lowercased (look here at "More Definitions": https://www.merriam-webster.com/dictionary/gov), but that could also mean "government". Though I guess that could also be surrounded with the `<abbr>` tag automatically. If you want me to add it, I can.
=> semanticate: Add abbreviation for Gov.

se/formatting.py
[https://en.wiktionary.org/wiki/Col.](https://en.wiktionary.org/wiki/Col.) (colonel). Can also be spelled without the period at times so I can add that as well, but I'm guessing it would be mostly spelled with the period because "col" by itself is also a word. 
Since we have abbreviations like St., Gov., Capt., Lt., etc. I think "Col." is a good addition.
=> semanticate: Add abbreviation for Col.

se/formatting.py
Per [the Manual](https://standardebooks.org/manual/1.0.0/8-typography#8.10.4.3), "MS." should be marked as an abbreviation but without class="initialism".
=> According to the Manual, "MS." is not an initialism

se/formatting.py
One of the chapter headings in my current production contains `On board the <i epub:type="se:name.vessel.ship">Atlantic</i>`: currently print-title renders this as `On board the`.
=> Teach print-title about italics

.github/workflows/se-test.yml
Current tests are not compatible with version 6.x of pytest.
Fixes #320
=> Restrict pytest version

.github/workflows/se-test.yml
Lint problem is resolved by pytest 6.0.1.
Fixes #322
=> Remove pytest version restriction

se/vendor/kobo_touch_extended/kobo.py
The Kobo build-chain breaks sentences into “kobo spans”. These shouldn’t affect the rendering, but as it stands a hair space in the content becomes a full space in the presentation.
This is most obvious with 4 dot ellipses, which we replicate with a full stop followed by a hair space followed by an ellipsis. This revised regex looks for that pattern and avoids splitting, causing the 4-dot ellipsis to render as expected.
=> Fix extra gap on Kobo before 4-dot ellipses

se/commands/lint.py, se/se_epub_lint.py
Message s-028 missed the filename so when this message was present in the linting messages a exception "AttributeError: 'NoneType' object has no attribute 'name'" occurred.
Added the filename part to the message and also added some checks to prevent this sort of exception.
=> Avoid unhandled exception when filename not present in linting message

se/vendor/kobo_touch_extended/kobo.py
This extends the work done to remove gaps in 4-dot ellipses to also include extra gaps between single/double close quotes.
This regex is getting unwieldy. If we have any more changes later on then we should probably decompose it.
=> Remove extraneous gap on Kobo in the middle of ’” pair

se/se_epub_lint.py
To resolve #330.
I ran this on several of my local copies of my completed books and did not get any false positives. I ran it on the Lieber that caused me to find this, and it reported all of the no-period abbreviations with no class on them.
=> Modify abbr with no class regex to catch abbreviations with no periods

se/formatting.py, se/se_epub_lint.py
This changes the regex in the t-030 check to allow optional numbers at the beginning or ending of the text. I used an asterisk at the end for things like D.C.10; I used one at the beginning because although I couldn't think of an abbreviation starting with two or more numbers, I was afraid there was some. :)
Per my email on the list, though, I'm not sure we shouldn't exception things like 2D/3D; that period looks weird to me on a single letter in the middle of a sentence.
=> Allow initialisms with numbers, e.g. D.C.4

LICENSE.md, se/data/fonts/league-spartan/league-spartan-bold.svg
Also fix the copyright reference in our League Spartan font file.
Sorry this is a bit wordy, but it turns out we’ve literally got tens of licences in use in tools.
=> Update licences to cover the current reality

README.md
The new version of pipx (0.15.5.0) fails with the existing documentation as it thinks `tools` is a package. We need to persuade it that it’s a directory.
=> Fix pipx dev install docs

se/se_epub_generate_toc.py
Add a second self.file_link in the error message outside the link so the filename will display in the error.
=> Fix toc_link method exception error

se/se_epub_lint.py
The variables in the m-043 message are reversed, i.e. the spine count is on the TOC portion and the TOC count on the spine portion. This fixes that.
=> Swap variables in m-043 message

se/se_epub_generate_toc.py
See my comments on issue #356.
=> Fix for print-toc where there are multiple hgroup children

se/images.py, se/se_epub_build.py
This is a proof-of-concept that at least begins the discussion. I changed images.py to generate the 2x version of the MathML images, then get the width/height of the image, divide them by 2, and put those in height and width attributes on the `img`.
This works for me on both a Mac and an iPad. I don't have any 1x displays to test it on.
One thing I noted is that the raw dimensions on the 2x versions are not divisible by 2, i.e. they're all odd. That seemed … odd. (Sorry.) Shouldn't they be if they're hiDPI versions?
=> Generate and use 2x MathML images

setup.py
This seems to drop cover generation for 800ms to 750ms on my machine.
=> Ensure Python 3.9 compatibility with latest pillow

se/se_epub_build.py
The code that generates classes to bypass spotty pseudoclass support was expecting to always run first, before the code that added generated epub-type classes. For reasons unknown, this is sometimes happening in reverse. When that happens, the code that generates pseudoclass replacements simply overwrites the now-earlier epub-type classes.
While a correct fix would be to structure the code to make it deterministic, we can at least work around it by backporting (and hence normalising) the class-setting logic from the epub-type routine to the pseudoclass routine.
With this applied we still see evidence of the non-determinism, but it’s no longer destructive (for example, we could see both `class="first-child epub-type-z3998-persona"` and `class="epub-type-z3998-persona first-child"`).
Fixes …
=> Fix missing generated epub-type-x classes

se/formatting.py
Used for page ranges: https://en.wikipedia.org/wiki/Acronym#Representing_plurals_and_possessives
I used this patch to fix a couple of books in the corpus: https://github.com/standardebooks/john-bunyan_the-pilgrims-progress/commit/33b88d3ff82ce18518d59d7804e09ef4e13e922a and https://github.com/standardebooks/john-stuart-mill_on-liberty/commit/65b6afa2a7d26cc0035d90be0ac9430ef379c18b.
=> Add pp. as an automatic abbreviation

README.md
The `java` cask in brew has been removed in favour of the non-cask `java`, which is just a synonym for `openjdk`. This works, but needs to be manually bound to system `java` (command taken from `brew info openjdk`).
Fixes https://github.com/standardebooks/tools/issues/371.
=> Fix README instructions for macOS Java installation

se/data/templates/compatibility.css, se/data/templates/core.css, tests/data/draft/jane-austen_unknown-novel/src/epub/css/core.css
iOS 13+ supports the `prefers-color-scheme` media query, so we can use that to invert images. The old and new versions play nicely together, in my testing on the latest versions at least.
Partially fixes https://github.com/standardebooks/tools/issues/377.
=> Fix dark mode in iOS13+ Books

se/data/templates/compatibility.css
This works on macOS 14 and lower, but is completely broken on iOS 12 and lower. Newer Apple OSs support the prefers-color-scheme media query in core.css.
=> Drop dark mode hack for older Apple Books

README.md
Not sure about Apple Silicon compatibility for everything yet. Also, `brew cask` is deprecated in favour of just `brew` now.
=> Update macOS install instructions

se/data/templates/compatibility.css, se/data/templates/core.css, tests/data/draft/jane-austen_unknown-novel/src/epub/css/core.css
This isn’t technically needed, but apparently it’s required for older Adobe RMSDK (as per https://www.mobileread.com/forums/showpost.php?p=4074195&postcount=41). Tested on Apple Books with no problem, and it’s valid CSS.
=> Add media to @media rules

se/epub.py, se/se_epub_build.py
I’ve left epub2 references in the kindle vendored code intact.
=> Remove outdated references to epub2 from code comments

se/se_epub_generate_toc.py
Just one spot where we'd omitted to call strip_notes().
=> Fixed endnote problem in generating ToC

se/se_epub.py
My prologues have been getting added twice to the spine, once where they should be and once towards the end, and I finally had time to investigate. It wasn't in the excluded files, so it was processed once explicitly and once implicitly in the list of filenames.
=> Fix prologue being added to spine twice

se/commands/create_draft.py
I've noticed that the tools are pretty bad at getting the LCSH IDs and a whole lot of them are `Unknown`. Turns out that it's a really simple fix. It was just that the previous query didn't specify that we wanted Subject Headings and searched through all the other schemes. And since we only looked at the first page of the results a bunch were lost.
Just one example, https://github.com/standardebooks/anne-bronte_the-tenant-of-wildfell-hall/blob/master/src/epub/content.opf#L32 It has all of them as `Unknown` even though 5 of the 6 should actually be known (and would be found with the new request query).
I'm not sure what the rules are regarding url encodings so I just left it unencoded and it works. If we have some code style rules I can of course encode them but it looks like …
=> Improve LCSH ID query

se/formatting.py
This is an annoying issue I find sometimes, where we have a name like V⸺ and semanticate thinks that it is a Roman numeral.
=> Fix semanticate with obscured names starting with V or X

se/se_epub_lint.py
In advance, sorry for the long explanation but I found a couple of issues that need a bit of explaining:
While working on Roughing It I came across a bug in the lint function: it would crash with nested at-rules because of the assumption that anything nested within an at-rule would be a selector. And just a clarification since some websites call a single @supports a nested at-rule: by nested at-rules I mean something like an @supports within an @media.
Nested at-rules are allowed according to the spec (https://www.w3.org/TR/css-conditional-3/#contents-of One example/more explanation can be found here https://www.w3.org/TR/css-conditional-3/#processing).
This code fixes that bug by recursion so technically it should work for any number of nested at-rules (tested up to three). I tested it …
=> Allow nested at-rules for lint 

se/se_epub_generate_toc.py
The change you made last night to move things around "magically" fixed `recompose-epub`; it now shows both the filename and the exception.
However, `print-toc` still only shows the filename. This is, I think, due to the `try` including both the `with open` and the `EasyHtmlTree` statements in `process_all_content`. A second try/except for the latter would work, but I just added `{ex}` to the existing message. I thought even if there was an error opening the file (as opposed to parsing it), it would be helpful to know what the actual error was, plus it keeps the code cleaner.
=> Add exception msg on file open/parse error

README.md
Since the instructions already reference `brew` for installing pre-requisites, and the kind of person who wants to install se bash completion is likely to already have installed brew bash-completions, this line should get them working. And the comment line provides a hint as to where to go looking for more info if bash completions are a new thing to them.
I don't use zsh myself but I think a very similar line would work for them.
=> Bash completion instructions for Mac OS

se/commands/create_draft.py
Discovered this while working on a separate (and since abandoned) PR. This data is regenerated later anyway, so doesn’t need to be prefilled.
=> Remove unnecessary prefilling of cover and titlepage

se/spelling.py
Gibbon has both of these as well as Mahomet.
Also, he uses Mussulman, Mussulmans, and Mullulmen, as well as Moslem(s?). Do we want to add those? If so I'll do another PR.
Wiki has museumann (two n's) as being a term for Nazi concentration camp prisoners, so I might search for Mussulman\b just in case.
=> Add additional Muhammad corrections

se/se_epub_generate_toc.py
Reolves an exception sometimes given when running print-toc. Exception: 'charmap' codec can't decode byte 0x81 in position 1142: character maps to <undefined>
=> add utf8 encoding to toc generation file open commands

se/epub.py
Changed this to do the posix path transform only for the cwd parameter in the python script instead of the xlst transform file.
I do not have a unix / mac to test this on to be sure it doesn't break the xlst processor there, but it does work on windows and the toc.ncx file is correctly generated.
=> use posix path for xslt transform

setup.py
Doing this would allow the toolkit to install on windows without also needing *6*GB of C++ compiler/header/sdk files to be installed, since psutil 5.8.0 has wheels for windows machines, and it appears they are going to continue supporting the wheels packages. 
https://github.com/giampaolo/psutil/blob/master/INSTALL.rst
=> bump psutil to 5.8.0

se/commands/create_draft.py, se/formatting.py, setup.py
The existing solution transposed characters like ö to o, but failed on characters like ø. We can instead use the Unidecode library, which covers automatically everything we’d want to theoretically do.
This adjusts create-draft and formatting to use the new library. It doesn’t change find-mismatched-diacritics, as identifying what a “diacritic” is here is a harder problem.
Any performance hit is in the noise in the tests that I ran. Fixes https://github.com/standardebooks/tools/issues/416.
=> Improve url generation

se/se_epub_generate_toc.py
I had a crash while running print-toc on Rights of Man. This fixes that potential crash.
=> Fixed a crash error where ToC level could not be determined

se/se_epub_lint.py
I missed the error messages themselves when I made the URI changes.
=> Correct URL references to URI in id.loc.gov errors

se/spelling.py
There seems to be a few places in the corpus where this is wrong. If you agree with the principle, I’ll update them.
=> Add mayday to problem spellings

se/se_epub.py
This was tricky, but it seems to be working. I tested it on Clarissa Harlowe (which had a couple of endnotes within endnotes). It worked fine but made no changes (but didn't lose the existing manually added notes at the end). 
I then added some additional dummy notes within that file and then renumbered and it worked fine.
=> Properly process endnotes WITHIN endnotes.xhtml itself

se/se_epub_lint.py
If a glossary is found, we first log all the glossary values, then walk through the text checking for usage. Any unused values can be added to the error messages.
There are a bunch of errors in _Hudibras’_ glossary xml that I’ll fix. I also tested it on _The Worst Journey_ and found that `strong breeze` was missing, so I’ll sweep all glossary files and fix them if you’re happy with this approach.
=> Add a lint check for glossary entries missing from the text

se/se_epub_lint.py
Bulfinch has an example of `<abbr>St.</abbr> Michael’s Mount` which can’t be string matched without this.
=> Strip elements before S-K-M linting

se/spelling.py
"cypher" was being replaced with "ccipher".
=> Fixed error on cypher in modernize spelling

se/se_epub.py
This removes a line of code which prevents temporarynon-numeric endnote ids such as note-17a or note-Nero227. When merging several sets of notes it is very useful to be able to use a non-numeric note id like those when first processing a project. Examples: merging the individual sets of notes in "The Twelve Caesars" and the three sets of notes for Lavengro and The Romany Rye (footnotes in each book and the editorial notes at the back). I prefixed the Lavengro ones with "LV" and the Romany Rye ones with "RR".
We don't need the existing note number anyway, as we'll be overwriting it.
=> Removed loading of existing note-ids, may not be integers and not needed

se/commands/create_draft.py
The colophon template was changed in https://github.com/standardebooks/tools/commit/e782004fcf326966f0bdce60fde4fc0c88e50b40, but `create-draft` was looking for the old template.
=> Fix missing translator block in new productions

se/se_epub_build.py
I tested `se build .` with and without errors, `se build -c .` with and without errors, and `se build --check-only .` with and without errors, and all produced the expected results (epub in first two combinations, no epub on last one).
=> Restore unconditional creation of compatible epub

se/spelling.py
There’s a few places in the corpus that would be affected by this standardisation. I’ll fix them if you’re happy with the PR.
=> Correct papier-mache -> papier-mâché

se/se_epub_lint.py
This is a first attempt; I doubt everything will be acceptable first try. I built a list of short messages for each kind of typo, then joined it to the t-042 message as a semi-colon delimited string. I tested with no typos, with a single kind, and with various multiples, the last one being:
```
Possible typo(s): doubled word; two periods; ldquo space; lsquo space; comma-period; comma-quote nospace; no punc b4 conj.
```
Here are the short descriptions I used, to save you from having to look through the code. Just let me know any (all?) of them you want to change and I'll update them. I purposely kept them short for when there might be multiples, but if you'd prefer everything spelled out and just have a really long message in those (rare) instances, no problem, just let me know.
``` …
```
=> Add semi-colon delimited description for each type of typo

se/se_epub.py
Alex:
This cleans things up a bit and does a check for "orphaned" endnotes (endnotes which exist in endnotes.xhtml but not referenced in the body text). Example run after hacking Lavengro about, deleting and duplicating some notes:
```
**Error**  Endnote errors found: 
Couldn’t find endnote(s) with anchor(s) note-276, note-312
Duplicate endnote anchors found for note-271, note-313
Ophaned endnote(s) found in endnotes.xhtml with anchor(s) note-271, note-313.
```
It occurs to me that check_endnotes could be useful as a stand-alone se command, not just called as part of renumber-endnotes. I'm not entirely sure how to achieve that.
=> Improved endnote check

se/commands/clean.py
Currently, running clean against a single xhtml file attempts to also pass it through the CSS processor, causing errors. The single file path of `get_target_filenames` can be updated to also check the file suffix.
An example of the error:
```
$ se clean src/epub/text/sulamith.xhtml --verbose
Processing /Users/robin/Code/standardebooks/corpus/aleksandr-kuprin_short-fiction_j-m-murray/src/epub/text/sulamith.xhtml 
... OK
Processing /Users/robin/Code/standardebooks/corpus/aleksandr-kuprin_short-fiction_j-m-murray/src/epub/text/sulamith.xhtml 
...     Error  File: 
/Users/robin/Code/standardebooks/corpus/aleksandr-kuprin_short-fiction_j-m-murray/src/epub/text/sulamith.xhtml. Exception:
EOF reached before {} block for a qualified rule.
```
=> Cleaning a single file should take account of extension

se/commands/create_draft.py
A few PG texts use single quotes for the header attributes, e.g.,
`<?xml version='1.0' encoding='utf-8'?>`
which causes `se create-draft` to fail. This happened [in Apr 2021](https://groups.google.com/g/standardebooks/c/Rgs0T2xVOzc/m/F_N05t9IAwAJ ), and it's present on others as well.
I took a whack at allowing either single or double quotes in the regex to remove the `encoding` attribute value from `pg_ebook_html` before parsing.
=> create-draft: Allows single or double quotes when parsing encoding attribute

se/spelling.py
As just discussed. I've also had reenforce, so I made the `ment` optional. (This also catches reenforced and reenforces.)
=> modernize-spelling: reenforce[ment] -> reinforce[ment]

se/se_epub_lint.py
This will need a minor corpus update.
```
$ rg 'xml:lang="uk"' --count
aleksandr-kuprin_yama_bernard-guilbert-guerney/src/epub/text/endnotes.xhtml:1
vladimir-korolenko_short-fiction_aline-delano_sergius-stepniak_william-westall_thomas-seltzer_the-ru/src/epub/text/in-bad-company.xhtml:2
vladimir-korolenko_short-fiction_aline-delano_sergius-stepniak_william-westall_thomas-seltzer_the-ru/src/epub/text/the-day-of-atonement.xhtml:20
vladimir-korolenko_short-fiction_aline-delano_sergius-stepniak_william-westall_thomas-seltzer_the-ru/src/epub/text/birds-of-heaven.xhtml:3
vladimir-korolenko_short-fiction_aline-delano_sergius-stepniak_william-westall_thomas-seltzer_the-ru/src/epub/text/the-blind-musician.xhtml:46
nikolai-gogol_short-fiction_claud-field_isabel-f-hapgood_vizetelly-and-company_george- …
```
=> Add Ukranian to the set of scripts that need a Latn suffix

se/commands/lint.py
They can take up all the space, pushing the actual error message down to nothing. This fixes the filename column to a slightly arbitrary 25 characters, which feels long enough for any book of chapters and most short fiction compilation stories.
Before:
```
┏━┳━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳
┃ ┃ Seve… ┃ File                                                                                                                       ┃
┡━╇━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇
│ │ Manu… │ a-sentimental-romance.xhtml …
```
=> Stop extremely long filenames from breaking lint output

se/formatting.py
1. The era replacements were checking for eoc but don't need to—there's no period on the abbreviations to function as an eoc—so I moved them above the section that starts with the eoc comment. Unrelated, those replacements look for an optional period after the first letter but not after the second; this leaves a trailing period after the replacement, e.g. "This happened in A.D. 387…" as "This happened in <abbr epub:type="se:era">AD</abbr>. 387…" This may be why I've seen this so often in reviews.
2. All of the ones using lookbehinds that included eoc now have one both before and after the tag. I tried putting \1 in the second one, hoping it would use the first one, but it didn't work.
3. Only one of the "Guess at adding eoc" replacements included eoc, and I did the same there, i.e. check …
=> Rework checks for eoc on abbreviations

README.md, se/commands/find_unusual_characters.py, se/completions/bash/se, se/completions/fish/se.fish, se/completions/zsh/_se
This makes it easy to find unexpected characters in a new transcription (for example).
Fixes https://github.com/standardebooks/tools/issues/476.
=> Add a find-unusual-characters command

setup.py
This is no longer recommended as of requests 2.26.0 (https://pyup.io/changelogs/requests/#2.26.0), and everything seems to work fine on macOS without it.
Fixes https://github.com/standardebooks/tools/issues/492.
=> Remove deprecated pyopenssl

se/se_epub_generate_toc.py
This is in response to this discussion about build-toc reporting errors when it strikes invalid heading structures.
=> Added check on valid roman numerals in headings

se/se_epub_lint.py
It’s feasible that the wat role could be present without images, so we don’t need an inverse lint.
Fixes https://github.com/standardebooks/tools/issues/500.
=> Add linting for required wat role for alt text

README.md
Homebrew installs into a different directory on ARM macs; we can discover this with `brew --prefix`. We can also mark it as tested on macOS 12.
=> Fix openjdk install instructions for ARM macs

se/commands/find_unusual_characters.py
These are all recommended for use in SEMOS. I haven’t included sup/sub numerals in the check because these regularly appear as OCR errors.
=> Remove some more usual characters from the unusual characters set

se/commands/renumber_endnotes.py, se/se_epub.py
I've expanded the report we get when verbose option is set for renumber-endnotes. It now generates a report like this:
`Found 418 endnotes and changed 389 endnotes.
note-31->note-30
note-32->note-31
note-33->note-32
note-34->note-33
note-35->note-34
note-36->note-35
note-37->note-36
note-38->note-37.
....`
The reason for this is to make it easy to search for changed endnote references which weren't inside actual notes. This is the case in Boswell's _Life of Johnson_, which has many references like this, e.g. "See _ante_, II, note 1." changed to references like `See <a href="endnotes.xhtml#note-1766">here</a>.` These note links _would not be changed_ by the current se renumber-endnotes and will need to be manually searched for and altered.
Having a list which gives a mapping from old note …
=> Extend renumber

se/se_epub_lint.py
It was slightly surprising to me that we aren’t already checking for this, but an easy thing to add. There are currently 33 instances of this in my clone of the corpus, but each would need to be double-checked against the source files to see whether it’s a problem with the period or the lowercase character.
(I couldn’t get any unicode-aware lowercase matchers to work, but it’s not a major issue.)
=> Add a check for a quote starting with a lowercase character after a period

se/se_epub_build.py
I spent today working on this and I think I have a satisfying fix for the Kobo poetry build issue. The code boils down to this:
1. Mark all of the original poetry verse spans with the `kobo-verse-span`. The `xpath` uses the predicate `[not(text()[normalize-space() != ''])]` to distinguish `p`s that represent stanzas from prose `p`s . The idea behind this is that a stanza `p` should not have any text nodes as its children since all of the text will be in the `span`s.
2. Update the poetry CSS so that the rules that target generic `span`s inside verses target spans with the class `kobo-verse-span`.
Here's an example of a de Cleyre poem with a broken header and footer before the fix:
This is the same poem with the fix:
Here is an example of a broken Newman epigraph:
This is the fixed …
=> build: Fix Kobo poetry build compatibility

se/se_epub_lint.py
Alex fixed this in _The Return of Tarzan_ already, but I’ve seen it in other productions in the past and it’s an easy lint check.
=> Lint for xml:lang="unk"

se/commands/renumber_endnotes.py, se/se_epub.py
Alex: there are a few people now needing this, and so far as I’ve been able to test it seems to work well. A reminder what it does is, after renumbering endnotes in the usual way, it hunts for and changes direct links to endnotes of the “see this note here” type.
=> Replace changed endnote refs

se/se_epub_lint.py
While working on _Benjamin Bunny_, the best way of getting high quality source imagery has been to copy down the individual scans from archive.org. These are provided in JPEG2000 format, with a .jp2 file extension. As all the images are full-page, I’ve just copied the .jp2 files into the ./images folder, but this causes lint to fail.
This patch simply ignores files with a .jp2 extension, typical for archive.org scans.
=> Don’t fail lint on presence of JPEG2000 files

se/se_epub_lint.py
The most obvious problem I frequently see is the halftitlepage language not matching the given book language. The other lint rules that don’t apply to ignored pages typically wouldn’t affect the halftitlepage, but it doesn’t hurt to run them.
=> Don’t ignore the halftitlepage when linting

se/commands/create_draft.py
Hi! I'm trying to use `se` on [NixOS](https://nixos.org/), which installs programs to a read-only directory tree (the "store"). When the Standard Ebooks tools are installed into the Nix store, the templates get installed there too, and when `se create-draft` copies them out of the store, they remain read-only, so it can't write the title etc. to them:
```pytb
Traceback (most recent call last):
File "/nix/store/r14fypa7gxingfk5k5f4vxp6dp7inbvc-python3.9-standardebooks-2.3.10/bin/.se-wrapped", line 9, in <module>
sys.exit(main())
File "/nix/store/r14fypa7gxingfk5k5f4vxp6dp7inbvc-python3.9-standardebooks-2.3.10/lib/python3.9/site-packages/se/main.py", line 81, in main
sys.exit(getattr(module, command_function)(args.plain_output))
File …
```
=> create-draft: Don't copy metadata from template files

.github/workflows/se-test.yml
I like this project, and saw you use Github Actions. 
Saw there's a couple things that could be simplier/more efficient, so thought I'd raise a PR :)
I tried testing locally with `act` but it's getting stuck downloading apt updates, so I thought I'd raise a PR.
Approval is needed to allow the Github Action workflow, thanks 👍
=> Github Actions updates

se/se_epub.py
I’ve bumped into this a few times: endnotes are in the step-by-step at number 10, but generating the spine is at number 18.
Also make sure each error is on a new line.
=> Add a spine hint for orphan errors on renumber-endnotes

se/commands/build_ids.py, se/se_epub_lint.py
This implements a function that checks for differences between the spine and the actual markup files. If files are found in the file system that aren’t in the spine we can error early. `lint` and `build-ids` have been amended to error in this way.
=> Allow system to error when spine doesn’t contain all markup

se/se_epub_lint.py
Found this by chance in the Gibbon review I’m doing; it’s an easy thing to lint for so we might as well. Fix up will be needed in the following (I’ll do that if you agree with this PR):
- alexandre-dumas_the-vicomte-de-bragelonne_george-routledge-and-co
- plato_dialogues_benjamin-jowett
- sun-tzu_the-art-of-war_lionel-giles
=> Lint for xml:lang attributes containing -latn, not -Latn

se/spelling.py
The charabanc substitution has been missing the 'h' since it was put in. My corpus isn't completely up-to-date, so not sure of the existing impact.
=> Correct charabanc substitution

se/commands/create_draft.py
Github has a limit of 100 characters for repo names. We currently lint for this, but don’t enforce this constraint during draft creation.
=> Truncate repo name to 100 chars max during create-draft

se/commands/shift_illustrations.py, se/completions/bash/se, se/completions/fish/se.fish, se/completions/zsh/_se, se/se_epub.py
Basically a clone of shift-endnotes in functionality; it shifts illustrations up and down. Requires all illustrations to be named illustration-x, but that’s as per SEMOS. It’s extension agnostic.
I needed this locally for Beatrix Potter which is currently at ~580 images. I’ve found some more to add in at around the 120 mark, which would have meant a lot of manual work.
=> Add a shift-illustrations command

se/se_epub_lint.py
François ran into an issue with lint running extremely long (he killed it after 10 minutes) when a long (45-50 characters) made-up word was wrapped in an `<em>` tag. It ran fine if it was an `<i>` tag.
Robin and I looked into it independently, and both confirmed that it was the regex that was checking for punctuation inside an `<em>` tag that was the problem, and the problem was due to insane amounts of recursion in the `(?:\w+?\s*)+` part of the regex. Robin found that lint choked after 26 characters inside the tag; I tested it in my text editor and it choked after 24. (My editor's limit is 10,000,000 recursions; that's what I mean by "insane".)
After looking at what the regex is doing (or at least what I think it's doing), this is what I wrote on the email thread:
>The zero or more …
=> Simplify and improve regex for checking punctuation inside em tags

se/se_epub_lint.py
These seem to be reasonably common initial monarchs from a check of the corpus, and it’ll be easy to add more as we go, if needed.
I’ll review the corpus for this set and fix.
=> Add a lint for some common initial monarchs with missing roman semantics

se/spelling.py
[MW](https://www.merriam-webster.com/dictionary/lagune) confirms that lagune is a variant spelling of "lagoon"
[ngrams](https://books.google.com/ngrams/graph?content=lagune%2Clagoon&year_start=1800&year_end=2019&corpus=26&smoothing=3) indicates that "lagune" was uncommon even in the 19th century
Also modernize use of ligature in "Linnaeus"
=> modernize-spelling: lagune -> lagoon

.github/workflows/se-test.yml, README.md, setup.py
A lot of our dependencies no longer support Python 3.6. Where this is the case, I’ve bumped them to that version and noted it with a comment. The only dependency that we can’t push to latest-or-3.6-compatible-version is chardet, where v5.0.0 isn’t compatible with the latest version of requests that we can go to.
I’ve tested these changes by running the test suite, and linting and building several productions.
=> Bump dependencies to as far as we can go with Python 3.6

setup.py
Addresses #561; after this change, I was able to run `pipx install --editable .` successfully.
=> Correct version specifier

se/spelling.py, tests/data/modernize-spelling/in/spelling_en_GB.xhtml, tests/data/modernize-spelling/out/spelling_en_GB.xhtml
I think this is the cleanest way of doing it.
There are a couple of instances of “maneuverd” in the corpus:
- https://github.com/standardebooks/henry-david-thoreau_essays/blob/f90bf024a96dcb289044357410cea3e625a5fe01/src/epub/text/chesuncook.xhtml#L72
- https://github.com/standardebooks/f-scott-fitzgerald_this-side-of-paradise/blob/c4113f15ee334f8d4c4bac5ca1be469f945421d1/src/epub/text/chapter-1-2.xhtml#L329
=> Fix manœuvred -> maneuvered / manoeuvred

se/spelling.py
Also Chilian -> Chilean. Fixes https://github.com/standardebooks/tools/issues/573.
=> modernize-spelling: Chili -> Chile

se/commands/split_file.py, se/data/templates/chapter-template.xhtml
Let's try this again. This puts the same smarts in split-file that exists in create-draft for guessing the language. It also modifies the template to have a LANG "variable" for split-file to replace.
=> Have split-file guess language like create-draft

.github/workflows/se-test.yml, README.md, pylintrc, se/__init__.py, se/commands/compare_versions.py, se/commands/create_draft.py, se/commands/find_unusual_characters.py, se/commands/interactive_replace.py, se/commands/unicode_names.py, se/easy_xml.py, se/formatting.py, se/images.py, se/main.py, se/se_epub.py, se/se_epub_build.py, se/se_epub_generate_toc.py, se/se_epub_lint.py, tests/helpers.py, tests/test_formatting.py
mypy has been broken on Macs for at least a couple of OS versions. Historically we haven’t wanted to upgrade to version 900 or beyond, partially because of the version of Python on the server, but partially because of the fact that typings are now modular.
Having investigated, I’m not too worried about the second point. To cover our needs, we need two additional packages: [types-requests](https://pypi.org/project/types-requests/) and [types-setuptools](https://pypi.org/project/types-setuptools/). I’ve added these to the readme and the Github action, but not to setup.py. They will never download automatically: that requires the `--non-interactive` flag when executing.
Having updated mypy it felt worth it to also update pylint. And once I’d bumped both of those, it turned out that there …
=> Fix mypy on Macs

se/spelling.py
We correct Michael Angelo to Michaelangelo, but Wiki, Brittanica, M-W, Oxford, Collins, et al all spell it Michelangelo. This adds a regex to correct all of the below to Michelangelo. We have around 70 occurrences of Michaelangelo in the corpus.
````
<p>Let's talk about sculptors. There's Michael Angelo, MichaelAngelo, Michael angelo, Michaelangelo, and Michelangelo.</p>
````
=> Correct spelling of Michelangelo

se/data/templates/content.opf, se/se_epub.py, se/se_epub_lint.py, tests/data/build-manifest/in/content.opf, tests/data/build-manifest/out/content.opf, tests/data/build-spine/in/content.opf, tests/data/build-spine/out/content.opf, tests/data/draft/jane-austen_unknown-novel/src/epub/content.opf, tests/data/formatting/in/meta.xhtml, tests/data/formatting/out/meta.xhtml, tests/data/lint/clean/content.opf, tests/data/lint/elements/content.opf, tests/data/lint/glossaries/content.opf, tests/data/lint/s-058/content.opf
Now that we’ve updated to epubcheck 5, we don‘t need our namespaced role hack. This removes it from the template and tests, and updates a couple of other places in the code that were checking for either role or se:role.
This will presumably need a find and replace across the corpus afterwards.
Incidentally, it looks like we’ve only had namespaced publisher roles since we put this in place?
=> Remove usage of se:role

se/se_epub_build.py
Looks like cairosvg 2.7.0 broke loading data URLs in source SVGs in “safe mode”, which causes the produced PNG to have a transparent background and the rendered JPG to end up with an all-black background. This was fixed in April (https://github.com/Kozea/CairoSVG/commit/2cbe3066e604af67c31d6651aa3acafe4ae0749d) but the latest 2.7.0 release was in March.
In the meantime, we can pass an unsafe flag through to svg2png which allows it to complete successfully. I don’t think this is a problem as we control the repos that build this data.
(I’m guessing this doesn’t affect the server as it’s obviously not producing black covers, but I’m unable to build an epub with a working cover locally on my mac.)
=> Fix cover building as only a black image

se/se_epub_generate_toc.py
This simple change seems to work, but it would be good to run it on the corpus after that is updated to the new structure.
=> Change to build-toc to accomodate hgroup changes

se/spelling.py
From the list: we catch Esthonian but not Esthonia, so expand the regex to handle both.
=> modernize-spelling: Expand Esthonian to also catch Esthonia

se/se_epub.py, tests/data/build-spine/in/halftitlepage.xhtml, tests/data/build-spine/in/misc-front.xhtml, tests/data/build-spine/out/content.opf, tests/data/build-spine/out/halftitlepage.xhtml, tests/data/build-spine/out/misc-front.xhtml
The existing behavior of putting all other front matter after the half title page is always wrong, per the Manual of Style.
=> build-spine: Order half title page after other front matter

se/se_epub_lint.py
I tested this on the entire corpus.
I did not get any new y-XXX codes, i.e. an instance of a y-XXX in a production that didn't already have an ignore present. That means (I think) that combining y-003/y-021 is still excluding everything that was excluded before.
I also did not get any lone m-048's, i.e. an instance where a t-042 was reported before but wasn't now. That means (I think) that it's not excluding _more_ than was excluded before.
I moved the second instance of y-002 to the top of the typos section, just for aesthetics (now they're processed in order from -002 to -032).
=> lint: Split typos (t-042) into separate codes (y-XXX)

se/se_epub_lint.py, tests/data/lint/content-out.txt
They are:
- `CONTRIBUTOR_ID`
- `CONTRIBUTOR_MARC`
- `CONTRIBUTOR_NACOAF_URI`
- `CONTRIBUTOR_NAME`
- `CONTRIBUTOR_SORT`
- `CONTRIBUTOR_WIKI_URL`
Found when reviewing a production where one of them had snuck through. I took the opportunity to sort the list in the order they appear in content.opf, and to add a secondary section for the colophon variables.
=> Add a few missing SE variables to lint

se/formatting.py, se/typography.py
I found that `9¾d.` in my current production hadn’t had an `abbr` added by semanticate; investigating that I found a handful of bugs / improvements.
=> Fix a few currency fraction bugs

se/se_epub_lint.py, tests/data/lint/c-006-out.txt, tests/data/lint/c-006/chapter-1.xhtml, tests/data/lint/c-006/dedication.xhtml, tests/data/lint/c-006/epigraph.xhtml, tests/test_lint.py
Added checks to se_epub_lint.py for missing dedication and epigraph CSS. These are placed close to the checks for missing poetry CSS, after what seemed to be the end of the poetry-related checks.
Added test data, test name, and output/golden file for missing dedication and epigraph CSS as well as all the other missing styles that lint checks for (span.elision; abbreviations with se:era, se:temperature, and z3998:acronym epub:type attributes; and elements with z3998:poem, :hymn, :verse, :lyrics epub:type attributes).
Closes #612.
=> Lint: checks and test for missing CSS

README.md
It’s not currently compatible with SE.
We should also probably update setup.py to restrict Python to a compatible version (`python_requires=">=3.7,<=3.11"`) but I’ll leave that up to you to decide @acabal.
=> Update macOS installation instructions to block Python 3.12

se/commands/compare_versions.py, se/se_epub_build.py
Use the `shutil.copytree` function as a direct replacement for `distutils.dir_util.copy_tree`. It offers a more straightforward interface and is well-supported in modern Python versions.
I noticed in a mailing list [thread](https://groups.google.com/g/standardebooks/c/63Sd9mLnfT4/m/Rucf1m3jAQAJ), that folks were getting stuck on this. It might also simplify installation instead of needed to pin the Python version to 3.11
I havent tested this yet, because the change itself was pretty straightforward and I was able to do it using Github's web interface. But if this sounds like a good idea, I am happy to setup the toolchain on my desktop and perform some tests.
=> Remove dependency on distutils

se/se_epub_lint.py
This is by no means ready for prime-time, but it's progressed far enough that it might be easier to discuss here than in the issue comments. Since almost everything has moved, I believe a diff will be next to useless, so you'll probably have to review the file in its entirety.
The goal was to make it easier to read and understand the flow, but also make it easier to know where to "do" things, i.e. when a new error is needed, an existing one needs to be changed, etc.
* Several chunks of code at the beginning of the "main" function moved to functions:
- _lint_metadata_checks, for the initial metadata checks
- _lint_css_checks, for the initial CSS checks
- _update_missing_styles
- _lint_image_checks (jpg/tif/png)
- _lint_svg_checks
- _lint_special_file_checks—colophon/imprint/endnotes/loi; …
=> Lint restructure

se/commands/create_draft.py, se/formatting.py
For example, this allows “Mrs. Seacole” to be entered as “Mrs. Seacole” to be kept on the same line during title generation.
As it stands, this commit changes non-breaking spaces back to normal spaces during the build process, so that they don’t show up in content.opf metadata for example. But that’s easily changed so that they’re retained.
Also, https://github.com/ppannuto/python-titlecase/issues/95 would remove the need for one of the changes, so I’ll remove it if that’s accepted.
=> Allow non-breaking spaces to tie together title blocks in draft creation

se/se_epub_generate_toc.py
I've altered where we check for a language tag in build-toc which seems to fix the problem in issue #628.
I've run a comparison between the results of new and old tocs and the only productions which don't match are either ones that always required a manual adjustment to the ToC or a handful of others which have unrelated issues (though some of these mean I should recheck my code in other areas.
For reference, the **non-matching** ToCs after this change to build-toc are as follows. The line numbers are in the ToC for each production.
- anatole-france_penguin-island_a-w-evans : line 132
- arthur-w-pinero_the-second-mrs-tanqueray : line 20
- friedrich-nietzsche_beyond-good-and-evil_helen-zimmern : line 236
- george-macdonald_phantastes : line 17
- …
=> Changes to build-toc to address issue #628

se/se_epub_generate_toc.py
Addresses issue #631 
In this production, part 1, part 2, part 3 etc are "special items" which we create when we find no headings. Such items were not assigned ids in the code. This meant that child items couldn't find their parent id, hence no indenting.
This pull request fixes that by assigning the file name (without the .xhtml) as the toc item id, and they are then found by child items.
=> Added getting the id of a special item

se/se_epub_generate_toc.py
This fixes the ToC mistake with unneeded indenting in the T. E. Lawrence Seven Pillars of Wisdom production and hopefully a few future productions.
=> Fixed spurious indenting problem for some cases

se/se_epub_generate_toc.py
Previously it just gave a file reference, which doesn’t help much in poetry compilations for example. This bit me on the Mina Loy compilation.
Before:
```
Error  Heading tagged as roman numeral is invalid: poetry.xhtml.
```
After:
```
Error  Heading tagged as roman numeral is invalid: XVIX in poetry.xhtml.
```
=> Show the problematic heading on roman error

se/se_epub_lint.py
Y-033 was added while the restructure was in-progress, and I apparently didn't get it into the correct function when I rebased.
I also left t-004 out of order, this just moves it up where it should be. There's some more re-ordering that needs to be done, but it's more extensive so I'll leave it for later.
I'm going to start looking at creating some additional lint tests, starting with the most complicated, e.g. maybe the couple identified in the instrumentation tests in #623, t-003, etc. Ones with multiple steps and/or ones with really complicated xpaths. If you have ones you're most interested in, let me know.
=> Move y-033 to typo function, move t-004

se/commands/create_draft.py, se/completions/bash/se, se/completions/fish/se.fish, se/completions/zsh/_se
Sometimes it’s nice to know what’s happening in `create-draft` as it’s working.
Potentially this should maybe be the default? Depends on how Unixy one feels I guess.
Example output:
```
~/C/s/corpus $ se create-draft -t "Test" -a "Test" -p 64384 -v
Creating ebook directory at /Users/robin/Code/standardebooks/corpus/test_test ...
Downloading ebook metadata from https://www.gutenberg.org/ebooks/64384 ...
Downloading ebook transcription from https://www.gutenberg.org/ebooks/64384.html.images ...
Building ebook structure in /Users/robin/Code/standardebooks/corpus/test_test ...
Cleaning transcription ...
Copying in standard files ...
Setting up ebook metadata ...
Initialising git repository ...
```
=> Add a verbose switch to create-draft

se/se_epub_lint.py
In creating the test for y-005, I had a `!.` at the end of a paragraph, and it wasn't caught. This adds an OR for EOL so that it will be.
I ran it against the corpus and didn't see that it caught anything, but I assume we _do_ want to catch it if it happened. (It's possible I could have missed something; every book failed lint because of the recent core change that hasn't been rolled out to the corpus yet.)
=> Improve y-005

se/formatting.py
When processing the text to calculate the reading ease score, we can first preprocess it to allow for verse that doesn’t end with punctuation. If we add a full stop at the end of verses just for the reading ease algorithm then we get more normal scores, and it shouldn’t affect other productions in a meaningful way.
1. Mina Loy’s Poetry goes from -128.58 to 42.45
2. William Carlos William’s Poetry goes from 79.5 to 79.6
3. Laurence Sterne’s Tristram Shandy goes from 51.35 to 51.55
4. Every other repo I’ve tried has no change.
=> Make the reading ease score cope better with free-form poetry

tests/README.md
Fix a couple of typos, add some clarification in the `data` section on which modules use which of the ebook directories.
=> Fix typos, clarify what uses each ebook directory

se/se_epub_lint.py
Per the discussion. I added an additional negative lookahead for the ellipsis, ran another test on the entire corpus, and the only differences were the ones with the ellipses. So, no false positives that I can see.
This will leave us with 86 works in the corpus that now have y-006 and/or y-013 errors (total of 98 errors). Do you want me to send a message to the editors to ask if they can help whittle it down? If so, and we find the text isn't a transcription error, would you consider fixing whatever is wrong Editorial? (It's going to be either adding a rsquo if the quote is valid, or reversing the rsquo if it's an elided word, or moving the comma/period inside the rsquo.)
=> Improve y-006 and y-013

se/browser.py, se/data/templates/content-white-label.opf, se/data/templates/content.opf, se/se_epub_build.py, se/se_epub_lint.py, tests/data/draftbook/jane-austen_draft-novel/src/epub/content.opf, tests/data/testbook/jane-austen_test-novel/src/epub/content.opf, tests/draft_commands/clean/test-1/golden/src/epub/content.opf, tests/draft_commands/clean/test-1/in/src/epub/content.opf, tests/lint/metadata/m-003/in/src/epub/content.opf, tests/lint/semantic/s-056/in/src/epub/content.opf, tests/lint/typos/y-001/in/src/epub/content.opf
This PR:
- Updates our accessibility conformance claim to WCAG 2.2
- Adds a lint check for `MathML` and `describedMath` accessibility features where appropriate
It also updates the build process to strip `MathML` and `describedMath` accessibility features from the compatible builds, and gets MathML building working again on non-Linux systems.
I guess we’ll want to update books with MathML with these new functionality, but we should wait until we’re building with this code.
=> Tweak some accessibility conformance claims

se/se_epub_lint.py
Let's try this again. I managed to insert some bad character or something in the previous one I closed.
I played with this a bit while determining what things to include in the test, and tested some xpaths in the corpus.
The first thing I noticed is that the `|[a-z]+ed` in the first test does not end in `\b`, so it will find "ed" in the middle of a word (and did in my testing), which I don't believe is what you want? That is, I'm assuming you're looking for past tense forms of various verbalization verbs, e.g. whispered, grunted, shrieked, etc., but don't want things like decidedly, dedication, shredding, etc.
Also, from the number of times it occurred in testing I think it would be worth adding "we" to the list of pronouns in the second test.
I ran the updated xpath against the corpus …
=> Improve y-014

se/se_epub_lint.py
This reverts commit 5b017a2afc87c0f425adb4a10fcdd87716e20296.
So sorry, Alex, I had a stupid typo in my test, and this needs to be reverted. Lesson learned: I'll just test with lint from now on rather than trying to save (granted, a lot of) time testing the regexes/xpath themselves.
=> Revert "Improve t-041, add period to list of checked punctuation"

se/se_epub_lint.py, tests/lint/typos/y-016/golden/y-016-out.txt, tests/lint/typos/y-016/in/src/epub/text/chapter-1.xhtml
As discussed in #676, along with the test for same.
=> Modify y-016 to properly exclude more than two periods in a row

tests/README.md
Cleaned up and standardized some language, clarified a couple of things, and corrected a couple of errors in the "run a single test" section for lint.
=> Clarify and correct few things in testing README

se/commands/find_unusual_characters.py
Noticed that a 〃 DITTO MARK is apparently too wide for a single character, which means that the width=1 setup in rich.table converts it to an ellipsis in the Terminal. Which was confusing.
Easy fix is just to remove the width constraint.
This was added in https://github.com/standardebooks/tools/commit/000d7c04a3b6ed6a520c3ab251714e9399c65db1, but doesn’t seem to be necessary for anything else I’m missing.
=> Fix broken overflow on wide unusual characters

se/commands/create_draft.py, se/data/templates/content.opf, se/data/templates/onix-white-label.xml, se/data/templates/onix.xml, se/se_epub.py, se/se_epub_build.py, se/se_epub_lint.py, tests/data/draftbook/jane-austen_draft-novel/src/epub/onix.xml, tests/data/testbook/jane-austen_test-novel/src/epub/onix.xml
This is a first set of accessibility metadata enhancements, after a review of ePub Accessibility 1.1 and ONIX 3.1. There are potentially more to follow, but those can be discussed in the accessibility metadata issue. Broadly, these:
- Update the default ONIX file to the latest spec and a more correct set of accessibility claims
- Update content.opf to claim support for the latest standard
- Add lint and build support for ONIX MathML feature claim
- Add a white label ONIX file that doesn’t link to SE’s group and doesn’t have SE set as the publisher
Fallout from this for the corpus:
- All books will need to be updated to the latest `onix.xml`
- All books will need the accessibility data updated in content.opf (easy find and replace)
- Books with MathML will need the additional MathML …
=> Accessibility metadata enhancements

se/spelling.py
Merriam‐Webster considers “sati” and “suttee” to be [the same word](https://www.merriam-webster.com/dictionary/sati).
[Wikipedia uses the spelling “sati,” and says:](https://en.wikipedia.org/wiki/Sati_(practice)#Etymology_and_usage)
> Sati appears in Hindi and Sanskrit texts, where it is synonymous with "good wife"; the term suttee was commonly used by Anglo-Indian English writers.…
>
> The spelling suttee is a phonetic spelling using 19th-century English orthography. The satī transliteration uses the more modern ISO/IAST (International Alphabet of Sanskrit Transliteration), the academic standard for writing the Sanskrit language with the Latin alphabet system.
(Note: that last usage is spelled with U+012B ī, but the rest of the article uses plain old *i*.)
I count about a dozen SE works …
=> modernize-spelling: suttee → sati

se/data/templates/content.opf, se/data/templates/onix.xml, tests/data/draftbook/jane-austen_draft-novel/src/epub/onix.xml, tests/data/testbook/jane-austen_test-novel/src/epub/onix.xml
Assuming you’re happy with https://github.com/standardebooks/web/pull/352, this adds a reference to it from the ONIX file template. Once this is merged then we can roll out the changes to the corpus.
That’ll be enough to close https://github.com/standardebooks/tools/issues/683. The ebooks and site could do with an accessibility audit, but that can be a seperate project.
=> Add a link to our accessibility page to the ONIX message

se/se_epub_lint.py, tests/lint/typography/t-074/golden/t-074-out.txt, tests/lint/typography/t-074/in/src/epub/text/chapter-1.xhtml
This changes the t-074 test to look for two consecutive single characters surrounded by dashes. As detailed in our discussion on the other PR, a single character between dashes finds more false positives than using two characters misses (e.g. this will allow to get rid of five ignore files that had to be created today).
I also got rid of the length limit, on the presumption that at least two characters is pretty likely to be a valid hit wherever it's found. (A run on the corpus turned up no false positives.)
(I had already done all this before I tried to pull the PR and saw you had made further changes to the test. Since I had covered more exclusions and had valid entries as well, I went ahead and left my test as it was. It covers everything yours did and more.)
I think a search for a …
=> Improve t-074 and its test

se/se_epub_lint.py, tests/lint/typos/y-022/golden/y-022-out.txt, tests/lint/typos/y-022/in/src/epub/text/chapter-1.xhtml, tests/lint/typos/y-024/golden/y-023-out.txt, tests/lint/typos/y-024/golden/y-024-out.txt, tests/lint/typos/y-024/in/src/epub/text/chapter-1.xhtml, tests/lint/typos/y-025/golden/y-025-out.txt, tests/lint/typos/y-025/in/src/epub/text/chapter-1.xhtml
Per discussion, this removes y-023. (I've tried several ways and can't figure out the t-003 change, so I'll leave that with you; it works right now, it's just regex instead of xpath, so it's not pressing). Per another issue I opened a few minutes ago, the rdquo test in y-025 duplicates y-012 (but not vice-versa), so I removed it. I also clarified the message on y-025, because what was there did not align with what was actually being checked (I've been confused by that message on more than one occasion, and have had to look at the code each time).
=> Remove y-023 from lint, add y-022 thru y-025 tests

se/se_epub_lint.py, tests/lint/typos/y-031/golden/y-031-out.txt, tests/lint/typos/y-031/in/src/epub/text/chapter-1.xhtml, tests/lint/typos/y-032/golden/y-032-out.txt, tests/lint/typos/y-032/in/src/epub/text/chapter-1.xhtml, tests/lint/typos/y-033/golden/y-033-out.txt, tests/lint/typos/y-033/in/src/epub/text/chapter-1.xhtml
With this, the tests for lint typos (y-xxx) are complete. At this rate we should be done with all of the lint tests around 2027. :) I think I'm going to take a little break from tests and try to actually read something, or at least work on something _to_ read.
Changes to lint:
*y-029*—since y-032 is checking for text on italics with epub:types, then y-029 doesn't need to. I added an exclusion for italics with epub:type.
*y-031* (all on second re:test)
1. It was  checking for whitespace followed by one of he/she/I, but there were leading `\b` on each of the he/she/I. Since we're checking for whitespace immediately before, the \b isn't needed (the whitespace already guarantees it).
2. The 'I' didn't have a `\b` _behind_ it, so it was matching anything that began with I, rather than I …
=> Improve y-029/y-031/y-032, add y-031 thru y-033 tests

se/se_epub_lint.py
There’s nothing Korean in the corpus yet but it doesn’t hurt to be proactive. There’s quite a few occurrences of `xml:lang="ja"`, which I’ll fix up now.
=> Lint for -Latn on the end of ja and ko lang attributes

.github/workflows/se-test.yml, README.md, pylintrc, se/commands/interactive_replace.py, se/commands/word_count.py, se/se_epub.py, se/se_epub_lint.py, tests/README.md
With the current version, pylint on Python 3.12 throws a bunch of errors. Updating it to version 3+ fixes the majority of these issues. I’ve also fixed the other outstanding ones, removed a couple of now-empty ignores from pylintrc, and updated one ignore to work with the latest mypy.
I’ve added `deprecated-method` to pylintrc to silence issues with importlib_resources. As that module is no longer necessary now that the Python we require is >3.6 (see description at https://pypi.org/project/importlib-resources/1.0.2/) I’ll follow this PR up with a PR that updates the codebase to importlib.resources instead. We can remove `deprecated-method` as part of that.
=> Update mypy / pylint / pytest and make everything work on latest Pythons

se/commands/find_unusual_characters.py
Each file can be processed independently, so processing them one at a time reduces total memory consumption.
=> Avoid keeping all files in memory for find-unusual-characters

mypy.ini, pylintrc, se/commands/compare_versions.py, se/commands/create_draft.py, se/commands/split_file.py, se/images.py, se/se_epub_build.py, se/se_epub_lint.py, se/spelling.py
We can replace this with importlib.resources instead, now that we’re baselined on a high enough level of Python.
I’ve included a small commit that doesn’t have any functional change, but tidies up a piece of inconsistent linting code I noticed while doing this.
I’ll leave it up to you to do the other couple of setup.py changes, unless you would like me to add a commit. They’re:
1. Remove the importlib_resources requirement as it’s no longer used in the codebase.
2. Bump the minimum Python version to 3.10. I don’t think there’s any value in going to 3.9: we’re not using it on the server for a start. Fedora 34 was the last version to ship with 3.9 and that went EOL over two years ago. On Mac people will just install whatever version necessary.
=> Remove use of importlib_resources throughout the codebase

se/easy_xml.py
I profiled se lint because it seemed to be surprisingly slow on a fairly small ebook repository. This revealed that half of the execution time was spent in the _replace_shorthand_namespaces method.
For the same repository, changing that method to use a named list (and therefore, only a single call to regex.sub) reduced the time spent in that method from ~15 seconds to ~5 seconds. This optimization is correct, and arguably easier to understand, because a single attribute can only have one prefix.
Using a named list also avoids the need to manually escape the prefixes before including them in the regex pattern, which this code was incorrectly skipping.
Finally, this change corrects a mistake in that method's documentation, as the : suffix is not retained in the output.
=> Use named list for regex substitution of namespace prefixes

se/easy_xml.py
On my local machine this reduces the execution time of `se lint` on Don Quixote from 55 seconds to 40 seconds.
Fixes #709
=> Skip regex.sub in get_attr method when attribute is un-namespaced

se/easy_xml.py
https://lxml.de/cssselect.html#the-cssselector-class
These selectors can only return elements, so there is no need to go through the result processing performed in the xpath method.
Fixes #711
=> Use compiled CSS selectors instead of reparsing their XPath

se/se_epub_lint.py
Such productions may contain an imprint or colophon, but don't necessarily use the same format as Standard Ebooks.
=> Disable colophon and imprint lints for white-label productions

se/easy_xml.py, tests/test_internals.py
Rather than using regex to remove tags and attributes after the fact.
https://lxml.de/api/lxml.etree-module.html#tostring
This also eliminates the need to perform HTML unescaping.
On my local machine, this reduces the time spent in the inner_text method on Don Quixote from 1.5 seconds to 0.04 seconds.
We add a basic test for the inner_text method in a preliminary commit to demonstrate that the behavior of the new implementation is equivalent.
=> Simplify inner_text implementation using lxml's text method

se/commands/build_loi.py, se/completions/bash/se, se/completions/fish/se.fish, se/completions/zsh/_se, se/data/templates/loi.xhtml, se/se_epub.py, tests/draft_commands/build-loi/test-1/golden/src/epub/content.opf, tests/draft_commands/build-loi/test-1/golden/src/epub/text/chapter-1.xhtml, tests/draft_commands/build-loi/test-1/golden/src/epub/text/chapter-2.xhtml, tests/draft_commands/build-loi/test-1/golden/src/epub/text/chapter-3.xhtml, tests/draft_commands/build-loi/test-1/golden/src/epub/text/loi.xhtml, tests/draft_commands/build-loi/test-1/golden/src/epub/toc.xhtml, tests/draft_commands/build-loi/test-1/in/src/epub/content.opf, tests/draft_commands/build-loi/test-1/in/src/epub/text/chapter-1.xhtml, tests/draft_commands/build-loi/test-1/in/src/epub/text/chapter-2.xhtml, tests/draft_commands/build-loi/test-1/in/src/epub/text/chapter-3.xhtml, tests/draft_commands/build-loi/test-1/in/src/epub/text/loi.xhtml, tests/draft_commands/build-loi/test-1/in/src/epub/toc.xhtml, tests/draft_commands/build-loi/test-2/golden/src/epub/content.opf, tests/draft_commands/build-loi/test-2/golden/src/epub/text/chapter-1.xhtml, tests/draft_commands/build-loi/test-2/golden/src/epub/text/chapter-2.xhtml, tests/draft_commands/build-loi/test-2/golden/src/epub/text/chapter-3.xhtml, tests/draft_commands/build-loi/test-2/golden/src/epub/text/loi.xhtml, tests/draft_commands/build-loi/test-2/golden/src/epub/toc.xhtml, tests/draft_commands/build-loi/test-2/in/src/epub/content.opf, tests/draft_commands/build-loi/test-2/in/src/epub/text/chapter-1.xhtml, tests/draft_commands/build-loi/test-2/in/src/epub/toc.xhtml, tests/stdout_commands/help/test-1/golden/help-test-1-out.txt, tests/stdout_commands/help/test-2/golden/help-test-2-out.txt, tests/test_draft_commands.py
Text from the `<figcaption>`, if any, is preferred over that from the `<img>`'s `alt` attribute, though this can be controlled on a per-ID basis. If the resulting text is empty, `default_link_text` is used.
If you prefer alternative behavior, particularly around what to do if a `<figcaption>` or `alt` text is empty, please let me know and I'm happy to change it.
=> Add build-loi command for updating an LoI file from <figure>s

se/se_epub_lint.py, tests/lint/semantic/s-041/golden/s-041-out.txt, tests/lint/semantic/s-041/in/src/epub/text/chapter-1.xhtml, tests/lint/semantic/s-041/in/src/epub/text/loi.xhtml
When the text being compared is from the image's alt attribute, since they are not used in that context.
=> Ignore non-breaking spaces and word joiners in s-041

se/css.py
I assume this was a find and replace for “prop” to “declaration” at some point.
Found this trying to track down an error in lint that turned out to be a specificity issue in my project instead, but might as well fix it if it’s found.
=> Fix broken naming in css.py comments

se/commands/create_draft.py, se/commands/word_count.py, se/formatting.py, se/se_epub.py, se/se_epub_generate_toc.py, se/se_epub_lint.py, se/typography.py, se/vendor/kobo_touch_extended/kobo.py
- [`MULTILINE`](https://docs.python.org/3/library/re.html#re.MULTILINE) is irrelevant unless ^ is used to match line starts
- [`IGNORECASE`](https://docs.python.org/3/library/re.html#re.IGNORECASE) is irrelevant when case-agnostic character classes are already being used (e.g. \w or \p{Letter}) or when only punctuation/spaces are being matched
- [`DOTALL`](https://docs.python.org/3/library/re.html#re.DOTALL) is irrelevant unless . is used to match all characters
=> Clean up regex flags

se/se_epub_lint.py, tests/lint/metadata/m-070/golden/m-070-out.txt, tests/lint/metadata/m-070/in/src/epub/glossary-search-key-map.xml, tests/lint/metadata/m-070/in/src/epub/text/chapter-1.xhtml
I ran the updated lint against the corpus entries that contain a glossary, and [it revealed a large number of unused entries](https://gist.github.com/apasel422/0fcaebed784fbc7fa45282cb1bbbe037). Some of these are typos (e.g. `Ygdrasil` as the glossary term vs `Ygdrasill` appearing in the text of Bulfinch's _Mythology_), while others are a singular/plural form that doesn't appear in that inflected form in the text (e.g. `trilobite` vs `trilobites` in _The Origin of Species_).
Fixes #731
=> Fix m-070 and add tests

se/se_epub_lint.py
This regex is being used to return a set of nodes, not match substrings, so the trailing context is irrelevant. The lint messages contain the result of calling to_string on the nodes.
=> Remove pointless trailing text from t-008 regex

se/commands/build_ids.py, se/formatting.py, se/se_epub.py, se/se_epub_lint.py
This also makes long lines easier to read and measure using a line-based profiler.
=> Use += with lists to avoid unnecessary temporary list creation

se/se_epub_build.py
Resolves part of #605
On the list it was raised that SE AZW3s do not show the correct current chapter location on Kindle. To fix this I proposed appending to the guide a reference element corresponding to the titlepage. 
Including a reference element corresponding to any text file seems to fix the Kindle issue. So given that build is already iterating through landmarks in the section edited here, another option would be just to append the bodymatter entry that’s already present in landmarks for each ebook. However, the only appropriate value of the `type` attribute for the bodymatter landmark's reference element is `text`, inclusion of which results in SE books opening at the first bodymatter file rather than at the titlepage, the latter being what we want (as far as I understand). …
=> Fix to build for current chapter location error affecting AZW3s on Kindle

se/se_epub_lint.py
The built cover is an SVG so isn’t being checked by `_lint_image_checks`, but the unbuilt cover image isn’t in src/epub/images so is also missing the file size check. This adds images/cover.jpg into those checks.
Images that are currently over 1500000 bytes (the lint threshold):
| Size | Project |
| ---- | ------- |
| 1516511 | [edgar-wallace_blue-hand](https://github.com/standardebooks/edgar-wallace_blue-hand) |
| 1560960 | [agatha-christie_the-mystery-of-the-blue-train](https://github.com/standardebooks/agatha-christie_the-mystery-of-the-blue-train) |
| 1623928 | [a-w-tozer_the-pursuit-of-god](https://github.com/standardebooks/a-w-tozer_the-pursuit-of-god) |
| 1657597 | [john-g-neihardt_a-cycle-of-the-west](https://github.com/standardebooks/john-g-neihardt_a-cycle-of-the-west) |
| …
=> Add filesize check for the cover JPG

se/formatting.py
A simple regex, based on https://en.wikipedia.org/wiki/Book_size#United_States
This shouldn’t clash with anything else given the lack of a space between the numbers and letters. This doesn’t cope with a full stop after the abbreviation but that seems rare and easily fixable manually.
Fixes https://github.com/standardebooks/manual/issues/167 (on second thoughts I shouldn’t have filed it against https://github.com/standardebooks/manual). I’ll fix what needs doing in the corpus if you’re happy with this.
=> Add book size abbreviations to semanticate

se/formatting.py, tests/draft_commands/clean/test-2/golden/src/epub/css/local.css, tests/draft_commands/clean/test-2/in/src/epub/css/local.css
This addresses two small issues with the CSS formatting in `se clean`.
1. An incorrect space is inserted between two `::`, if these colons follow an opening `(`.
```css
p:nth-of-type(1)::before{
```
is currently changed to
```css
p:nth-of-type(1): :before{
```
The regex responsible for this sees the opening `(` and then adds a space after the first `:` it finds. The comment in the code explains that this is to fix the colon in media queries such as `(prefers-color-scheme: dark)`, but it also affects colons outside the parentheses.
This can be fixed by making the regex stop at the closing `)`. I think this shouldn't break anything else. The media query example still works.
2. Strings in the CSS output are not escaped. The raw string from the parser is directly written to the cleaned …
=> Two CSS formatting bugs in se clean

se/se_epub_build.py, tests/ebook_commands/build/test-1/build-command, tests/ebook_commands/build/test-1/golden/extracted/epub/css/local.css, tests/ebook_commands/build/test-1/in/src/epub/css/local.css, tests/test_ebook_commands.py
In the Apple Books app on iOS, full-page images are often spread over multiple pages:
Example from [How the other half lives](https://standardebooks.org/ebooks/jacob-riis/how-the-other-half-lives):
The full-page figures are styled with `max-height: 100vh` (see [CSS from the book](https://github.com/standardebooks/jacob-riis_how-the-other-half-lives/blob/d2abddbfcc1cb6c4d406ec7dcfd28b1b4a68fa16/src/epub/css/local.css#L106-L112)), but the compatibility code in `se build` converts the `vh` units to percentages. Apparently this doesn't work for full-page images in Apple Books. (Cantook on iOS doesn't have this problem: it show the images on a single page.)
This patch changes the compatibility code so that it still adds the percentages, but also keeps the `vh` and `vm` units for readers that …
=> Preserve vh/vw units in compatibility CSS

se/typography.py, tests/draft_commands/typogrify/test-1/golden/typogrify.xhtml, tests/draft_commands/typogrify/test-1/in/typogrify.xhtml
Typogrify removes the space between a whole numbers and a fraction, but it currently also removes the space after a comma. Since the comment only mentions "whole numbers", the regexp probably shouldn't include commas.
=> typogrify: Do not remove space between a comma and a fraction

se/formatting.py, tests/draft_commands/semanticate/test-1/golden/semanticate.xhtml, tests/draft_commands/semanticate/test-1/in/semanticate.xhtml
`se semanticate` has a regexp that wraps lowercase `i` to a Roman numeral `<span>`. The regexp also does this to `i`s inside attributes:
```html
<a href="appendix-i.xhtml">
```
becomes
```html
<a href="appendix-<span epub:type="z3998:roman">i</span>.xhtml">
```
This patch adds a lookahead clause to check that the `i` is not inside an open tag.
=> semanticate: i inside a tag is not a Roman numeral

se/se_epub.py, tests/draft_commands/build-loi/test-1/golden/src/epub/text/chapter-1.xhtml, tests/draft_commands/build-loi/test-1/golden/src/epub/text/loi.xhtml, tests/draft_commands/build-loi/test-1/in/src/epub/text/chapter-1.xhtml
`se build-loi` copies non-block-level elements from the `<figcaption>` to the LoI. If the caption contains an `<a>` tag, such as an endnote reference, this creates a nested `<a>`:
```html
<a href="chapter-1.xhtml#f-10">Figure.<a href="endnotes.xhtml#note-8" id="noteref-8" epub:type="noteref">8</a></a>
```
This patch:
* removes noteref `<a>`s entirely;
* removes other `<a>` tags as well, but keeps their contents.
=> build-loi: Remove links and noterefs from figcaption

se/spelling.py
One one [false positive](https://github.com/standardebooks/suetonius_the-lives-of-the-caesars_j-c-rolfe/blob/2b4162ca25b94adb9ab7f1dbbd79f121aa1999e8/src/epub/text/book-6.xhtml#L39) in the corpus: “the most celebrated pleaders vied with one another in bringing before him, not trifling and **brief cases** according to the usual custom.”
I’ve updated the rest already.
=> Modernize brief case to briefcase

se/data/templates/proofreading.css
I didn’t realise the proofreading CSS existed, have been doing this manually in my productions.
=> Highlight time elements when proofreading

se/se_epub_lint.py, se/spelling.py, tests/lint/typos/y-024/golden/y-024-out.txt
There‘s an obvious trend in ngrams for this: https://books.google.com/ngrams/graph?content=a%C3%ABrial%2Caerial&year_start=1800&year_end=2022&corpus=en&smoothing=3
Looking at the corpus, 19 productions currently use this; will modernize if this is merged.
=> Modernize aërial -> aerial

se/data/templates/compatibility.css
Apple Books has a specific behaviour for tables: if you click on them you get a scannable zoomable popup of the whole table. This is really nice functionality, until you realise that we use tables to lay drama out.
A fix is to block events on drama tables. Obviously we have some links (for example endnotes) inside drama that need to remain clickable, so we unblock for those.
I’ve tested this on Agamemnon: the table click behaviour is blocked, while the endnotes continue to pop up as expected. One change we could make is to make this specific to Apple Books though? Up to you.
=> Fix wrong click behaviour in Apple Books with drama

se/spelling.py
Also add a warning that naïf as a noun is the correct usage.
I’ve covered the rest of the corpus: the two remaining naïfs are part of French text.
=> Modernize naïf -> naive

se/spelling.py
We still want to drop the hyphen though. It should also work in the plural.
In the corpus there’s “street Arab” with a capital in the following productions that I’ll fix:
- alexandre-dumas_the-count-of-monte-cristo_chapman-and-hall
- arthur-conan-doyle_a-study-in-scarlet
- arthur-conan-doyle_the-memoirs-of-sherlock-holmes
- arthur-conan-doyle_the-sign-of-the-four
- d-h-lawrence_women-in-love
- emile-gaboriau_monsieur-lecoq_laura-e-kendall
- emile-gaboriau_the-slaves-of-paris_charles-scribners-sons
- erskine-childers_the-riddle-of-the-sands
- ethel-voynich_the-gadfly
- fergus-hume_the-mystery-of-a-hansom-cab
- freeman-wills-crofts_the-cask
- honore-de-balzac_father-goriot_ellen-marriage
- honore-de-balzac_shorts-from-scenes-from-private-life_clara-bell_ellen-marriage
- …
=> modernize-spelling: lowercase street arab

se/data/words
This is in M-W unabridged. I don't know you feel about that for hyphenation purposes. It is a word, if an uncommon one, so I thought we would want to correct bond-slave to bondslave.
There are a few occurrences of bond-slave(s) in the corpus; I'll correct them if this is accepted.
=> Add bondslave(s) to hyphenation word list

se/data/templates/compatibility.css
This was causing an undesired inability to select text on Kobo. Of course, it turns out that we also can’t select text on Books either, but at least this fixes non-Books scenarios.
I tried a bunch of other CSS to see if I could word around the problem with no luck. I think the next steps would be to experiment with `display: grid` for browsers that support it…
=> Restrict blocking of table popup to just Apple Books

README.md
The directory's location can differ across systems. Fedora places it at `~/.local/share/pipx/venvs/` while macOS places it at `~/.local/pipx/venvs/`.
=> Derive `pipx`'s venv directory automatically

CHANGELOG.md, README.md, se/commands/build_loi.py, se/commands/build_title.py, se/commands/build_toc.py, se/commands/create_draft.py, se/completions/fish/se.fish, se/completions/zsh/_se
This PR fixes a large amount of typos. Some of the fixes in the first commit are subjective, so please let me know if I need to revert them.
=> Fix many typos

se/data/words
A few more words run across either in reviews or in my current production, all in M-W.
While adding mantelshelf, I noticed we have both mantelpiece(s) and mantlepiece(s). M-W [says](https://www.merriam-webster.com/dictionary/mantle) (scroll down to the Did You Know?) that mantel and mantle aren't really synonyms, although the latter is sometimes used, "especially in American English," for the former. Ngrams reflects that; mantlepiece is barely above zero, mantelpiece is a couple of order of magnitudes more common. (In English fiction; it's even more pronounced in English in general.)
So, I wonder if we should change mantle-?piece to mantelpiece in spelling.py, and remove mantlepiece(s) from words? There are 45 occurrences of mantlepiece in the corpus that would need to be changed.
Ditto …
=> Add words to hyphenated words list

se/typography.py, tests/draft_commands/british2american/test-1/golden/b2a.xhtml, tests/draft_commands/british2american/test-1/in/b2a.xhtml
Here's the code and test. I assembled the test file from real paragraphs in _Decline and Fall_ and _Good Companions_. I also included at least one instance where b2a doesn't do the right thing, so we have an example if we figure out a way to improve it in the future.
I've attached a file that shows differences in processing the test file with the old command vs the new one. As previously, it includes color codes so should be viewed with `less -R`.
A couple of notes:
1. The existing tests for consecutive quotes was testing for a word-joiner and thin-space, rather than our currently used hairspace. I don't know if that's what we used to do or what, but I updated it to look for the hairspace (and made it optional, in case they hadn't run typogrify yet).
2. In the test for dialect with the …
=> Improve british2american command

se/commands/extract_ebook.py
Ran into this when trying to bulk extract a bunch of `.epub`s which made it harder to track down the broken files.
=> Add filepath to error when extracting non ebooks

se/typography.py, tests/draft_commands/british2american/test-1/golden/b2a.xhtml
I've tested another half-dozen or so of our books that had b2a run on them, including two Dickens, which have a lot of dialect. The good news is that things are much improved. I also found three more words to add to the reverse quote dialect regex, and removed is—the latter occurs far more often as the real word in an opening quote than as dialect. (I've only found the ‘is as dialect in one book, vs ‘is as the real word in all but one of the others.)
I also fixed a comment in the overview, and added one on the double quote regexes.
=> Add additional dialect, fix and improve comments on convert_british_to_american

se/data/words
Merriam-Webster does have springtide (meaning springtime), but it also has spring tide (meaning tides at full/new moons), and all or almost all of the usages of spring-tide in the corpus is the latter. Thus, removing the dash automatically is the wrong thing to do.
=> Remove springtide(s) that was recently added.

se/data/templates/content.opf
Change to content.opf template.
Should refine transcriber-2 rather than transcriber-1
=> refiner typo

se/commands/find_mismatched_dashes.py, se/commands/find_mismatched_diacritics.py, se/commands/unicode_names.py
For some reason (Python 3.13?) I’m getting an error with urllib.parse:
```
AttributeError: module 'urllib' has no attribute 'parse'
```
The only usage of urllib in the project is to run parse, so importing urllib.parse fixes the error.
=> Fix errors with urllib.parse

se/commands/recompose_epub.py, se/completions/bash/se, se/completions/fish/se.fish, se/completions/zsh/_se, se/se_epub.py
See #827 for motivation and context.
After running with the new `--image-files` (`-i`) flag, all I had to do was replace `src="../images` with `src="./images` and zip up the HTML output plus the `images` folder to build this Gutenberg-compatible version: https://ebookmaker.pglaf.org/cache/20250511164828/ (link expires in 3 days).
=> recompose-epub: Add --image-files flag. Fixes #827

se/commands/typogrify.py
If you use an uuid as identifier, typogrify changes the hyphens.
=> Don't typogrify `<dc:identifier>`

se/se_epub_build.py
The filename generation now safely cleans more unsafe characters (ex. `"`, `#`, `!` etc.) from possible identifiers.
Addresses #844.
=> Change: BuildMessage.build now cleans more characters disallowed in filenames, when generating a filename from dc:identifier.

se/spelling.py
The Author's Note of An Outcast of the Islands by Joseph Conrad contains the "tete a tete" spelling.
=> modernize-spelling: tete a tete -> tête-à-tête

se/commands/create_draft.py
This causes an `m-003` lint error later on in the production process.
=> create-draft: fix missing trailing slash on PGDP url

setup.py
`se lint` frequently emits
```
[...]/lib/python3.12/site-packages/smartypants.py:271: SyntaxWarning: invalid escape sequence '\S'
if re.match("\S", prev_token_last_char):
```
This is an upstream bug in smartypants: https://github.com/justinmayer/smartypants.py/pull/21
A fix was included in June 16 release 2.0.2: https://github.com/justinmayer/smartypants.py/issues/25#issuecomment-2980447643
I don't believe it will break anything as this is a minor change, but I of course am not the editor-in-chief! Submitting PR with due deference & respect.
=> Fix `SyntaxWarning: invalid escape sequence`

se/formatting.py, tests/draft_commands/semanticate/test-1/golden/semanticate.xhtml, tests/draft_commands/semanticate/test-1/in/semanticate.xhtml
Add `>` to the list of things that can't be at the end of a roman numeral, to exclude valid MathML tags. Add the corresponding MathML to the semanticate test.
=> semanticate: Exclude roman numerals found at the end of a tag

se/commands/build_svg_titles.py, tests/stdout_commands/help/test-1/golden/help-test-1-out.txt, tests/stdout_commands/help/test-2/golden/help-test-2-out.txt
This adds a new `se build-svg-titles` command that copies the `alt` text from the XHTML files to the `<title>` elements in the corresponding SVG files. This saves time when adding or updating these descriptions and makes it easier to keep them synchronized.
Would this be useful to add to the tools?
* Copying the descriptions from the `alt` attributes to the SVG files makes the most sense, I think, because you would also have to add `alt` tags for any non-SVG images, so this keeps everything in one place.
* I am not sure if `build-svg-titles` is the ideal name, but it matches the `build-title` command that has a somewhat similar function.
* This command doesn't re-indent the SVG files or correct the `<title>` position (that is for `se clean`), but if you run it on a properly indented file …
=> Add a build-svg-titles command

se/se_epub_build.py
Fixes srcset to include the full image path, and the same comment correction and dup character replacement removal in the aborted footnote PR.
=> Fix srcset
